// DO NOT EDIT THIS FILE
// IT IS AUTOGENERATED BY `sbtgen.sc` SCRIPT
// ALL CHANGES WILL BE LOST


import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}

import sbtrelease.ReleaseStateTransformations._
import scala.sys.process._

lazy val refreshFlakeTask    = taskKey[Unit]("Refresh flake.nix")
lazy val regenerateGoldens   = taskKey[Unit]("Regenerate Layer A goldens")
lazy val verifyGoldens       = taskKey[Unit]("Verify Layer A goldens against legacy compiler")
lazy val runWireFixtures     = taskKey[Unit]("Run Layer B wire-byte fixtures (placeholder for PR-03.2)")
lazy val runCrossLangInterop = taskKey[Unit]("Run Layer C cross-language interop (placeholder for PR-03.4)")


enablePlugins(SbtgenVerificationPlugin)

ThisBuild / libraryDependencySchemes += "io.circe" %% "circe-core" % VersionScheme.Always

ThisBuild / libraryDependencySchemes += "io.circe" %% "circe-core_sjs1" % VersionScheme.Always

lazy val `idealingua-v1-model` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("idealingua-v1/idealingua-v1-model"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % V.scalatest % Test,
      "io.7mind.izumi" %%% "fundamentals-collections" % Izumi.version,
      "io.7mind.izumi" %%% "fundamentals-platform" % Izumi.version,
      "io.7mind.izumi" %%% "fundamentals-functional" % Izumi.version
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full),
      "org.scala-lang" % "scala-reflect" % scalaVersion.value % Provided
    ) else Seq.empty }
  )
  .settings(
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    coverageEnabled := false,
    scalaJSLinkerConfig := { scalaJSLinkerConfig.value.withModuleKind(ModuleKind.CommonJSModule) }
  )
  .enablePlugins(IzumiPlugin)
lazy val `idealingua-v1-modelJVM` = `idealingua-v1-model`.jvm
lazy val `idealingua-v1-modelJS` = `idealingua-v1-model`.js

lazy val `idealingua-v1-core` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("idealingua-v1/idealingua-v1-core"))
  .dependsOn(
    `idealingua-v1-model` % "test->compile;compile->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % V.scalatest % Test,
      "com.lihaoyi" %%% "fastparse" % V.fastparse,
      "io.7mind.izumi" %%% "fundamentals-platform" % Izumi.version
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    coverageEnabled := false,
    scalaJSLinkerConfig := { scalaJSLinkerConfig.value.withModuleKind(ModuleKind.CommonJSModule) }
  )
  .enablePlugins(IzumiPlugin)
lazy val `idealingua-v1-coreJVM` = `idealingua-v1-core`.jvm
lazy val `idealingua-v1-coreJS` = `idealingua-v1-core`.js

lazy val `idealingua-v1-runtime-rpc-scala` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("idealingua-v1/idealingua-v1-runtime-rpc-scala"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % V.scalatest % Test,
      "io.7mind.izumi" %%% "fundamentals-bio" % Izumi.version,
      "io.7mind.izumi" %%% "fundamentals-platform" % Izumi.version,
      "org.typelevel" %%% "cats-core" % Izumi.Deps.fundamentals_bioJVM.org_typelevel_cats_core_version,
      "org.typelevel" %%% "cats-effect" % Izumi.Deps.fundamentals_bioJVM.org_typelevel_cats_effect_version,
      "io.circe" %%% "circe-parser" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version,
      "io.circe" %%% "circe-literal" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version,
      "io.circe" %%% "circe-generic-extras" % V.circe_generic_extras,
      "dev.zio" %%% "zio" % Izumi.Deps.fundamentals_bioJVM.dev_zio_zio_version % Test,
      "dev.zio" %%% "zio-interop-cats" % Izumi.Deps.fundamentals_bioJVM.dev_zio_zio_interop_cats_version % Test,
      "dev.zio" %%% "izumi-reflect" % Izumi.Deps.fundamentals_bioJVM.dev_zio_izumi_reflect_version % Test
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full),
      "org.scala-lang" % "scala-reflect" % scalaVersion.value % Provided,
      "io.circe" %%% "circe-derivation" % V.circe_derivation
    ) else Seq.empty },
    libraryDependencies ++= {
      val version = scalaVersion.value
      if (version.startsWith("0.") || version.startsWith("3.")) {
        Seq(
          "io.circe" %%% "circe-generic" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version
        )
      } else Seq.empty
    }
  )
  .settings(
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    coverageEnabled := false,
    scalaJSLinkerConfig := { scalaJSLinkerConfig.value.withModuleKind(ModuleKind.CommonJSModule) }
  )
  .enablePlugins(IzumiPlugin)
lazy val `idealingua-v1-runtime-rpc-scalaJVM` = `idealingua-v1-runtime-rpc-scala`.jvm
lazy val `idealingua-v1-runtime-rpc-scalaJS` = `idealingua-v1-runtime-rpc-scala`.js
  .settings(
    libraryDependencies ++= Seq(
      "io.github.cquiroz" %%% "scala-java-time" % V.scala_java_time % Test
    )
  )

lazy val `idealingua-v1-runtime-rpc-http4s` = project.in(file("idealingua-v1/idealingua-v1-runtime-rpc-http4s"))
  .dependsOn(
    `idealingua-v1-runtime-rpc-scalaJVM` % "test->compile;compile->compile",
    `idealingua-v1-test-defs` % "test->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test,
      "org.http4s" %% "http4s-dsl" % V.http4s,
      "org.http4s" %% "http4s-circe" % V.http4s,
      "org.http4s" %% "http4s-blaze-server" % V.http4s_blaze,
      "org.http4s" %% "http4s-blaze-client" % V.http4s_blaze,
      "org.asynchttpclient" % "async-http-client" % V.asynchttpclient,
      "io.7mind.izumi" %% "logstage-core" % Izumi.version,
      "io.7mind.izumi" %% "logstage-adapter-slf4j" % Izumi.version
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua-v1-transpilers` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("idealingua-v1/idealingua-v1-transpilers"))
  .dependsOn(
    `idealingua-v1-core` % "test->compile;compile->compile",
    `idealingua-v1-runtime-rpc-scala` % "test->compile;compile->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % V.scalatest % Test,
      "org.scala-lang.modules" %%% "scala-xml" % V.scala_xml,
      "org.scalameta" %%% "scalameta" % V.scalameta,
      "io.7mind.izumi" %%% "fundamentals-bio" % Izumi.version,
      "io.circe" %%% "circe-parser" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version,
      "io.circe" %%% "circe-literal" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version,
      "io.circe" %%% "circe-generic-extras" % V.circe_generic_extras
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full),
      "io.circe" %%% "circe-derivation" % V.circe_derivation
    ) else Seq.empty },
    libraryDependencies ++= {
      val version = scalaVersion.value
      if (version.startsWith("0.") || version.startsWith("3.")) {
        Seq(
          "io.circe" %%% "circe-generic" % Izumi.Deps.fundamentals_json_circeJVM.io_circe_circe_core_version
        )
      } else Seq.empty
    }
  )
  .settings(
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    Test / fork := true
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    coverageEnabled := false,
    scalaJSLinkerConfig := { scalaJSLinkerConfig.value.withModuleKind(ModuleKind.CommonJSModule) }
  )
  .enablePlugins(IzumiPlugin)
lazy val `idealingua-v1-transpilersJVM` = `idealingua-v1-transpilers`.jvm
  .dependsOn(
    `idealingua-v1-test-defs` % "test->compile",
    `idealingua-v1-runtime-rpc-typescript` % "test->compile",
    `idealingua-v1-runtime-rpc-go` % "test->compile",
    `idealingua-v1-runtime-rpc-csharp` % "test->compile"
  )
lazy val `idealingua-v1-transpilersJS` = `idealingua-v1-transpilers`.js

lazy val `idealingua-v1-test-defs` = project.in(file("idealingua-v1/idealingua-v1-test-defs"))
  .dependsOn(
    `idealingua-v1-runtime-rpc-scalaJVM` % "test->compile;compile->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test,
      "dev.zio" %% "zio" % Izumi.Deps.fundamentals_bioJVM.dev_zio_zio_version,
      "dev.zio" %% "zio-interop-cats" % Izumi.Deps.fundamentals_bioJVM.dev_zio_zio_interop_cats_version,
      "dev.zio" %% "izumi-reflect" % Izumi.Deps.fundamentals_bioJVM.dev_zio_izumi_reflect_version
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua-v1-runtime-rpc-typescript` = project.in(file("idealingua-v1/idealingua-v1-runtime-rpc-typescript"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua-v1-runtime-rpc-go` = project.in(file("idealingua-v1/idealingua-v1-runtime-rpc-go"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua-v1-runtime-rpc-csharp` = project.in(file("idealingua-v1/idealingua-v1-runtime-rpc-csharp"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua-v1-compiler` = project.in(file("idealingua-v1/idealingua-v1-compiler"))
  .dependsOn(
    `idealingua-v1-transpilersJVM` % "test->compile;compile->compile",
    `idealingua-v1-runtime-rpc-scalaJVM` % "test->compile;compile->compile",
    `idealingua-v1-runtime-rpc-typescript` % "test->compile;compile->compile",
    `idealingua-v1-runtime-rpc-go` % "test->compile;compile->compile",
    `idealingua-v1-runtime-rpc-csharp` % "test->compile;compile->compile",
    `idealingua-v1-test-defs` % "test->compile;compile->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test,
      "com.typesafe" % "config" % V.typesafe_config
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } }
  )
  .enablePlugins(JavaAppPackaging, IzumiPlugin)

lazy val `idealingua-v1-test-harness` = project.in(file("idealingua-v1/idealingua-v1-test-harness"))
  .dependsOn(
    `idealingua-v1-transpilersJVM` % "test->compile;compile->compile",
    `idealingua-v1-compiler` % "test->compile;compile->compile",
    `idealingua-v1-test-defs` % "test->compile;compile->compile"
  )
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % V.scalatest % Test
    ),
    libraryDependencies ++= { if (scalaVersion.value.startsWith("2.")) Seq(
      compilerPlugin("org.typelevel" % "kind-projector" % V.kind_projector cross CrossVersion.full)
    ) else Seq.empty }
  )
  .settings(
    crossScalaVersions := Seq(
      "3.8.3",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind.izumi",
    scalacOptions ++= Seq(
      s"-Xmacro-settings:product-name=${name.value}",
      s"-Xmacro-settings:product-version=${version.value}",
      s"-Xmacro-settings:product-group=${organization.value}",
      s"-Xmacro-settings:scala-version=${scalaVersion.value}",
      s"-Xmacro-settings:scala-versions=${crossScalaVersions.value.mkString(":")}"
    ),
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val ltEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ <= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => ltEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n+") }
        case _ => Seq.empty
      }
    },
    Compile / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Compile / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / unmanagedSourceDirectories ++= {
      val version = scalaVersion.value
      val crossVersions = crossScalaVersions.value
      import Ordering.Implicits._
      val gtEqVersions = crossVersions.map(CrossVersion.partialVersion).filter(_ >= CrossVersion.partialVersion(version)).flatten
      (Test / unmanagedSourceDirectories).value.flatMap {
        case dir if dir.getPath.endsWith("scala") => gtEqVersions.map { case (m, n) => file(dir.getPath + s"-$m.$n-") }
        case _ => Seq.empty
      }
    },
    Test / testOptions += Tests.Argument("-oDF"),
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "2.13.18") => Seq(
        "-release:8",
        "-explaintypes",
        "-Xsource:3-cross",
        "-P:kind-projector:underscore-placeholders",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning",
        "-Wconf:cat=optimizer:warning",
        "-Wconf:cat=other-match-analysis:error",
        "-Vimplicits",
        "-Vtype-diffs",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wdead-code",
        "-Wextra-implicit",
        "-Wnumeric-widen",
        "-Woctal-literal",
        "-Wvalue-discard",
        "-Wunused:_",
        "-Wmacros:default",
        "-Ycache-plugin-class-loader:always",
        "-Ycache-macro-class-loader:last-modified"
      )
      case (_, "3.8.3") => Seq(
        "-release:17",
        "-Xkind-projector:underscores",
        "-Yretain-trees",
        "-no-indent",
        "-explain",
        "-explain-types",
        "-explain-cyclic",
        "-Xmax-inlines:64",
        "-Ybackend-parallelism",
        math.min(16, math.max(1, sys.runtime.availableProcessors() - 1)).toString,
        "-Wenum-comment-discard",
        "-Wimplausible-patterns",
        "-Wnonunit-statement",
        "-Wopt:all",
        "-Wrecurse-with-default",
        "-Wshadow:private-shadow",
        "-WunstableInlineAccessors",
        "-Wunused:all",
        "-Wvalue-discard",
        "-Wwrong-arrow",
        "-Wconf:any:verbose",
        "-Wconf:name=UnusedNonUnitValue:silent",
        "-Wconf:name=ValueDiscarding:silent",
        "-Wconf:msg=eta-expanded even though:silent",
        if (insideCI.value) "-Wconf:any:error" else "-Wconf:any:warning"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions ++= { (isSnapshot.value, scalaVersion.value) match {
      case (false, "2.13.18") => Seq(
        "-opt:l:inline",
        "-opt-inline-from:izumi.**"
      )
      case (false, "3.8.3") => Seq(
        "-opt",
        "-opt-inline:izumi.**"
      )
      case (_, _) => Seq.empty
    } },
    scalacOptions -= "-Wconf:any:error",
    scalacOptions += "-Wconf:msg=nowarn:silent",
    scalacOptions += "-Wconf:msg=pattern var charIn:silent",
    excludeDependencies ++= { (isSnapshot.value, scalaVersion.value) match {
      case (_, "3.8.3") => Seq(
        "com.lihaoyi" % "sourcecode_2.13"
      )
      case (_, _) => Seq.empty
    } },
    Compile / unmanagedSourceDirectories += (LocalRootProject / baseDirectory).value / "idealingua-v1" / "idealingua-v1-test-defs" / "golden" / "scala",
    regenerateGoldens := {
      val log      = streams.value.log
      val repoRoot = (LocalRootProject / baseDirectory).value.getAbsolutePath
      log.info("regenerateGoldens: starting")
      val cp = (Compile / fullClasspath).value.files
      val r  = (Compile / runner).value
      r.run("izumi.idealingua.harness.RegenerateMain", cp, Seq(repoRoot), log)
        .failed.foreach(e => throw e)
      log.info("regenerateGoldens: done")
    },
    verifyGoldens := {
      val log      = streams.value.log
      val repoRoot = (LocalRootProject / baseDirectory).value.getAbsolutePath
      log.info("verifyGoldens: starting")
      val cp = (Compile / fullClasspath).value.files
      val r  = (Compile / runner).value
      r.run("izumi.idealingua.harness.VerifyMain", cp, Seq(repoRoot), log)
        .failed.foreach(e => throw new MessageOnlyException(e.getMessage))
      log.info("verifyGoldens: all goldens match")
    },
    runWireFixtures := {
      val log      = streams.value.log
      val repoRoot = (LocalRootProject / baseDirectory).value.toPath
      log.info("runWireFixtures: starting")
      val cp = (Compile / fullClasspath).value.files
      val r  = (Compile / runner).value
      r.run("izumi.idealingua.harness.WireFixturesMain", cp, Seq(repoRoot.toString), log)
        .failed.foreach(e => throw new MessageOnlyException(e.getMessage))
      def countJsons(p: java.nio.file.Path): Long = if (java.nio.file.Files.exists(p)) {
        val s = java.nio.file.Files.walk(p)
        try s.filter(x => java.nio.file.Files.isRegularFile(x) && x.toString.endsWith(".json")).count()
        finally s.close()
      } else 0L
      val sc = countJsons(repoRoot.resolve("idealingua-v1/idealingua-v1-test-defs/wire-fixtures/scala"))
      val tc = countJsons(repoRoot.resolve("idealingua-v1/idealingua-v1-test-defs/wire-fixtures/typescript"))
      val cc = countJsons(repoRoot.resolve("idealingua-v1/idealingua-v1-test-defs/wire-fixtures/csharp"))
      log.info(s"runWireFixtures: all $sc Scala + $tc TypeScript + $cc CSharp fixtures match")
    },
    runCrossLangInterop := {
      val log      = streams.value.log
      val repoRoot = (LocalRootProject / baseDirectory).value.toPath
      log.info("runCrossLangInterop: starting cross-language matrix")
      val cp = (Compile / fullClasspath).value.files
      val r  = (Compile / runner).value
      r.run("izumi.idealingua.harness.CrossLangMain", cp, Seq(repoRoot.toString), log)
        .failed.foreach(e => throw new MessageOnlyException(e.getMessage))
      log.info("runCrossLangInterop: matrix verified")
    }
  )
  .enablePlugins(IzumiPlugin)

lazy val `idealingua` = (project in file(".agg/idealingua-v1-idealingua"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true,
    crossScalaVersions := Nil
  )
  .enablePlugins(IzumiPlugin)
  .aggregate(
    `idealingua-v1-modelJVM`,
    `idealingua-v1-modelJS`,
    `idealingua-v1-coreJVM`,
    `idealingua-v1-coreJS`,
    `idealingua-v1-runtime-rpc-scalaJVM`,
    `idealingua-v1-runtime-rpc-scalaJS`,
    `idealingua-v1-runtime-rpc-http4s`,
    `idealingua-v1-transpilersJVM`,
    `idealingua-v1-transpilersJS`,
    `idealingua-v1-test-defs`,
    `idealingua-v1-runtime-rpc-typescript`,
    `idealingua-v1-runtime-rpc-go`,
    `idealingua-v1-runtime-rpc-csharp`,
    `idealingua-v1-compiler`,
    `idealingua-v1-test-harness`
  )

lazy val `idealingua-jvm` = (project in file(".agg/idealingua-v1-idealingua-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true,
    crossScalaVersions := Nil
  )
  .aggregate(
    `idealingua-v1-modelJVM`,
    `idealingua-v1-coreJVM`,
    `idealingua-v1-runtime-rpc-scalaJVM`,
    `idealingua-v1-runtime-rpc-http4s`,
    `idealingua-v1-transpilersJVM`,
    `idealingua-v1-test-defs`,
    `idealingua-v1-runtime-rpc-typescript`,
    `idealingua-v1-runtime-rpc-go`,
    `idealingua-v1-runtime-rpc-csharp`,
    `idealingua-v1-compiler`,
    `idealingua-v1-test-harness`
  )

lazy val `idealingua-js` = (project in file(".agg/idealingua-v1-idealingua-js"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true,
    crossScalaVersions := Nil
  )
  .aggregate(
    `idealingua-v1-modelJS`,
    `idealingua-v1-coreJS`,
    `idealingua-v1-runtime-rpc-scalaJS`,
    `idealingua-v1-transpilersJS`
  )

lazy val `idealingua-v1-jvm` = (project in file(".agg/.agg-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true,
    crossScalaVersions := Nil
  )
  .aggregate(
    `idealingua-jvm`
  )

lazy val `idealingua-v1-js` = (project in file(".agg/.agg-js"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true,
    crossScalaVersions := Nil
  )
  .aggregate(
    `idealingua-js`
  )

lazy val `idealingua-v1` = (project in file("."))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    ThisBuild / scalacOptions ++= Seq(
      s"-Xmacro-settings:sbt-version=${sbtVersion.value}",
      s"-Xmacro-settings:git-repo-clean=${com.github.sbt.git.SbtGit.GitKeys.gitUncommittedChanges.value}",
      s"-Xmacro-settings:git-branch=${com.github.sbt.git.SbtGit.GitKeys.gitCurrentBranch.value}",
      s"-Xmacro-settings:git-described-version=${com.github.sbt.git.SbtGit.GitKeys.gitDescribedVersion.value.getOrElse("")}",
      s"-Xmacro-settings:git-head-commit=${com.github.sbt.git.SbtGit.GitKeys.gitHeadCommit.value.getOrElse("")}"
    ),
    Global / onChangedBuildSource := ReloadOnSourceChanges,
    ThisBuild / publishMavenStyle := true,
    ThisBuild / scalacOptions ++= Seq(
      "-encoding",
      "UTF-8",
      "-feature",
      "-unchecked",
      "-deprecation",
      "-language:higherKinds"
    ),
    ThisBuild / javacOptions ++= Seq(
      "-encoding",
      "UTF-8",
      "-source",
      "1.8",
      "-target",
      "1.8",
      "-deprecation",
      "-parameters",
      "-Xlint:all",
      "-XDignore.symbol.file"
    ),
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    coverageEnabled := false,
    ThisBuild / organization := "io.7mind.izumi",
    ThisBuild / publishTo := {
      // https://github.com/sbt/sbt/issues/8131
      if (isSnapshot.value) {
        Some(
          "central-snapshots" at "https://central.sonatype.com/repository/maven-snapshots/"
        )
      } else {
        localStaging.value
      }
    }
    ,
    ThisBuild / credentials ++= {
      val credTarget = Path.userHome / ".sbt" / "secrets" / "credentials.sonatype-new.properties"
      if (credTarget.exists) {
        Seq(Credentials(credTarget))
      } else {
        Seq.empty
      }
    },
    ThisBuild / credentials ++= {
      val credTarget = Path.userHome / ".sbt" / "secrets" / "credentials.sonatype-nexus.properties"
      if (credTarget.exists) {
        Seq(Credentials(credTarget))
      } else {
        Seq.empty
      }
    },
    ThisBuild / credentials ++= {
      val credTarget = file(".") / ".secrets" / "credentials.sonatype-nexus.properties"
      if (credTarget.exists) {
        Seq(Credentials(credTarget))
      } else {
        Seq.empty
      }
    },
    refreshFlakeTask := {
      val log = streams.value.log
      val rootDir = (ThisBuild / baseDirectory).value
      val lockfileOutput = rootDir / "deps.lock.json"
      val refreshCommand = Process(
        Seq("nix", "develop", "--command", "mdl", ":flake-refresh"),
        rootDir
      )
      val result = refreshCommand.!(log)
      if (result != 0) {
        throw new MessageOnlyException(s"flake.nix update failed: mdl exited with $result")
      }
      val gitAdd = Process(Seq("git", "add", lockfileOutput.getPath), rootDir)
      val gitResult = gitAdd.!(log)
      if (gitResult != 0) {
        throw new MessageOnlyException(s"git add failed with exit code $gitResult")
      }
    },
    releaseProcess := Seq[ReleaseStep](
      checkSnapshotDependencies,
      inquireVersions,
      runClean,
      runTest,
      setReleaseVersion,
      releaseStepTask(refreshFlakeTask),
      commitReleaseVersion,
      tagRelease,
      //publishArtifacts,
      setNextVersion,
      commitNextVersion,
      pushChanges
    ),
    ThisBuild / homepage := Some(url("https://izumi.7mind.io")),
    ThisBuild / licenses := Seq("BSD-style" -> url("http://www.opensource.org/licenses/bsd-license.php")),
    ThisBuild / developers := List(
              Developer(id = "7mind", name = "Septimal Mind", url = url("https://github.com/7mind"), email = "team@7mind.io"),
            ),
    ThisBuild / scmInfo := Some(ScmInfo(url("https://github.com/7mind/izumi"), "scm:git:https://github.com/7mind/izumi.git")),
    ThisBuild / scalacOptions += s"""-Xmacro-settings:scalatest-version=${V.scalatest}""",
    ThisBuild / scalacOptions += s"""-Xmacro-settings:scalajs-version=1.21.0""",
    ThisBuild / scalacOptions += s"""-Xmacro-settings:bundler-version=${"0.21.1"}""",
    ThisBuild / scalacOptions += s"""-Xmacro-settings:sbt-js-version=${"1.0.2"}""",
    ThisBuild / scalacOptions += s"""-Xmacro-settings:crossproject-version=${"1.3.2"}""",
    ThisBuild / scalacOptions += s"-Xmacro-settings:is-ci=${insideCI.value}"
  )
  .enablePlugins(IzumiPlugin)
  .aggregate(
    `idealingua`
  )
