package idltest.services

import _root_.cats.effect.Async
import _root_.io.circe.{Json, parser}
import izumi.functional.bio.{Error2, Exit, F, IO2}
import izumi.idealingua.runtime.rpc.{
  IRTDecodingException,
  IRTMethodId,
  IRTMethodName,
  IRTMissingHandlerException,
  IRTServerMultiplexor,
  IRTServiceId,
  IRTUnathorizedRequestContextException,
}
import org.http4s.{HttpRoutes, Request, Response, Status}
import org.http4s.circe._
import org.http4s.dsl.Http4sDsl

/** MCP / HTTP4s bridge for `TestService`. Generated by
  * `DomainServiceMcpRenderer` per plan §3.1. Mb2 scope: all 5
  * `Output` variants (Void / Singular / Struct / Algebraic /
  * Alternative) dispatch uniformly through `mux.invokeMethod` per
  * plan D5; the static `wrap` flag is derived from
  * `OutputWrapPolicy.isWrapped` (§3.2).
  *
  * Effect typeclasses: bifunctor `F[+_, +_]: IO2: Error2` is the
  * user-facing surface (mirrors the IRT runtime + plan D3); http4s
  * routes additionally need `cats.effect.Async[F[Throwable, _]]` at the
  * edge for its DSL (`Ok(...)`, `req.as[Json]`, etc.) — same pattern
  * `HttpServer.scala` uses.
  */
object TestServiceMcpRoutes {

  /** tools/list envelope loaded from classpath resource at first access
    * (D8(b)). The translator emits `mcp/TestService.mcp.json` alongside
    * this source file when `emitMcpBridge = true`.
    */
  private lazy val toolsListJson: Json = {
    val stream = getClass.getClassLoader.getResourceAsStream("mcp/TestService.mcp.json")
    require(stream != null, "Missing classpath resource: mcp/TestService.mcp.json")
    try parser.parse(scala.io.Source.fromInputStream(stream, "UTF-8").mkString).toTry.get
    finally stream.close()
  }

  private val toolName_unitToUnit = "idltest.services.TestService.unitToUnit"
  private val methodId_unitToUnit = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("unitToUnit"))
  private val toolName_anotherVoid = "idltest.services.TestService.anotherVoid"
  private val methodId_anotherVoid = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("anotherVoid"))
  private val toolName_unitResult = "idltest.services.TestService.unitResult"
  private val methodId_unitResult = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("unitResult"))
  private val toolName_parameterless = "idltest.services.TestService.parameterless"
  private val methodId_parameterless = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("parameterless"))
  private val toolName_simpleMethod = "idltest.services.TestService.simpleMethod"
  private val methodId_simpleMethod = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleMethod"))
  private val toolName_simpleIntMethod = "idltest.services.TestService.simpleIntMethod"
  private val methodId_simpleIntMethod = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleIntMethod"))
  private val toolName_simpleMethodWithGenerics = "idltest.services.TestService.simpleMethodWithGenerics"
  private val methodId_simpleMethodWithGenerics = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleMethodWithGenerics"))
  private val toolName_simple = "idltest.services.TestService.simple"
  private val methodId_simple = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simple"))
  private val toolName_simpleEnum = "idltest.services.TestService.simpleEnum"
  private val methodId_simpleEnum = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleEnum"))
  private val toolName_simpleEnum2 = "idltest.services.TestService.simpleEnum2"
  private val methodId_simpleEnum2 = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleEnum2"))
  private val toolName_returnsList = "idltest.services.TestService.returnsList"
  private val methodId_returnsList = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("returnsList"))
  private val toolName_returnsMap = "idltest.services.TestService.returnsMap"
  private val methodId_returnsMap = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("returnsMap"))
  private val toolName_simpleGoReserved = "idltest.services.TestService.simpleGoReserved"
  private val methodId_simpleGoReserved = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleGoReserved"))
  private val toolName_simpleVoid = "idltest.services.TestService.simpleVoid"
  private val methodId_simpleVoid = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("simpleVoid"))
  private val toolName_greetSingularOut = "idltest.services.TestService.greetSingularOut"
  private val methodId_greetSingularOut = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetSingularOut"))
  private val toolName_greetImplicitStructOut = "idltest.services.TestService.greetImplicitStructOut"
  private val methodId_greetImplicitStructOut = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetImplicitStructOut"))
  private val toolName_greetImplicitStructMultilineSyntax = "idltest.services.TestService.greetImplicitStructMultilineSyntax"
  private val methodId_greetImplicitStructMultilineSyntax = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetImplicitStructMultilineSyntax"))
  private val toolName_greetImplicitStructureMultilineCurlyBracesSyntax = "idltest.services.TestService.greetImplicitStructureMultilineCurlyBracesSyntax"
  private val methodId_greetImplicitStructureMultilineCurlyBracesSyntax = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetImplicitStructureMultilineCurlyBracesSyntax"))
  private val toolName_greetAlgebraicOut = "idltest.services.TestService.greetAlgebraicOut"
  private val methodId_greetAlgebraicOut = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetAlgebraicOut"))
  private val toolName_greetAlgebraicMultilineSyntax = "idltest.services.TestService.greetAlgebraicMultilineSyntax"
  private val methodId_greetAlgebraicMultilineSyntax = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("greetAlgebraicMultilineSyntax"))
  private val toolName_alternative = "idltest.services.TestService.alternative"
  private val methodId_alternative = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("alternative"))
  private val toolName_alternativeSame = "idltest.services.TestService.alternativeSame"
  private val methodId_alternativeSame = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("alternativeSame"))
  private val toolName_alternativeGeneric = "idltest.services.TestService.alternativeGeneric"
  private val methodId_alternativeGeneric = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("alternativeGeneric"))
  private val toolName_alternativeGeneric2 = "idltest.services.TestService.alternativeGeneric2"
  private val methodId_alternativeGeneric2 = IRTMethodId(IRTServiceId("TestService"), IRTMethodName("alternativeGeneric2"))

  def routes[F[+_, +_]: IO2: Error2, C](
    mux: IRTServerMultiplexor[F, C],
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): HttpRoutes[F[Throwable, _]] = {
    import dsl._
    HttpRoutes.of[F[Throwable, _]] {
      case GET -> Root / "mcp" / "tools" / "list" =>
        Ok(toolsListJson)

      case req @ POST -> Root / "mcp" / "tools" / "call" =>
        req.as[Json].flatMap { body =>
          val nameOpt  = body.hcursor.downField("name").as[String].toOption
          val argsJson = body.hcursor.downField("arguments").as[Json].getOrElse(Json.obj())
          nameOpt match {
            case Some(`toolName_unitToUnit`) =>
              call(req, argsJson, methodId_unitToUnit, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_anotherVoid`) =>
              call(req, argsJson, methodId_anotherVoid, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_unitResult`) =>
              call(req, argsJson, methodId_unitResult, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_parameterless`) =>
              call(req, argsJson, methodId_parameterless, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleMethod`) =>
              call(req, argsJson, methodId_simpleMethod, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleIntMethod`) =>
              call(req, argsJson, methodId_simpleIntMethod, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleMethodWithGenerics`) =>
              call(req, argsJson, methodId_simpleMethodWithGenerics, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simple`) =>
              call(req, argsJson, methodId_simple, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_simpleEnum`) =>
              call(req, argsJson, methodId_simpleEnum, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleEnum2`) =>
              call(req, argsJson, methodId_simpleEnum2, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_returnsList`) =>
              call(req, argsJson, methodId_returnsList, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_returnsMap`) =>
              call(req, argsJson, methodId_returnsMap, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleGoReserved`) =>
              call(req, argsJson, methodId_simpleGoReserved, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_simpleVoid`) =>
              call(req, argsJson, methodId_simpleVoid, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_greetSingularOut`) =>
              call(req, argsJson, methodId_greetSingularOut, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_greetImplicitStructOut`) =>
              call(req, argsJson, methodId_greetImplicitStructOut, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_greetImplicitStructMultilineSyntax`) =>
              call(req, argsJson, methodId_greetImplicitStructMultilineSyntax, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_greetImplicitStructureMultilineCurlyBracesSyntax`) =>
              call(req, argsJson, methodId_greetImplicitStructureMultilineCurlyBracesSyntax, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_greetAlgebraicOut`) =>
              call(req, argsJson, methodId_greetAlgebraicOut, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_greetAlgebraicMultilineSyntax`) =>
              call(req, argsJson, methodId_greetAlgebraicMultilineSyntax, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_alternative`) =>
              call(req, argsJson, methodId_alternative, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_alternativeSame`) =>
              call(req, argsJson, methodId_alternativeSame, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_alternativeGeneric`) =>
              call(req, argsJson, methodId_alternativeGeneric, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_alternativeGeneric2`) =>
              call(req, argsJson, methodId_alternativeGeneric2, wrap = true, extractCtx, mux, dsl)
            case Some(other) if other.startsWith("idltest.services.TestService.") =>
              Ok(mcpError(-32601, s"Method not found: $other"))
            case _ =>
              NotFound()
          }
        }
    }
  }

  private def call[F[+_, +_]: IO2: Error2, C](
    req: Request[F[Throwable, _]],
    args: Json,
    methodId: IRTMethodId,
    wrap: Boolean,
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    mux: IRTServerMultiplexor[F, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): F[Throwable, Response[F[Throwable, _]]] = {
    import dsl._
    (for {
      ctx <- extractCtx(req)
      raw <- mux.invokeMethod(methodId)(ctx, args)
    } yield {
      val shaped = if (wrap) Json.obj("result" -> raw) else raw
      Json.obj(
        "content" -> Json.arr(Json.obj(
          "type" -> Json.fromString("text"),
          "text" -> Json.fromString(shaped.noSpaces),
        )),
        "structuredContent" -> shaped,
        "isError"           -> Json.False,
      )
    }).sandboxExit.flatMap {
      case Exit.Success(j)                                          => Ok(j)
      case Exit.Error(_: IRTMissingHandlerException, _)             => Ok(mcpError(-32601, "Method not found"))
      case Exit.Error(_: IRTDecodingException, _)                   => Ok(mcpError(-32602, "Invalid arguments"))
      case Exit.Error(_: _root_.io.circe.Error, _)                  => Ok(mcpError(-32602, "Invalid arguments"))
      case Exit.Error(_: IRTUnathorizedRequestContextException, _)  => F.pure(Response[F[Throwable, _]](status = Status.Unauthorized))
      case _                                                        => Ok(mcpError(-32603, "Internal error"))
    }
  }

  private def mcpError(code: Int, msg: String): Json = Json.obj(
    "content"           -> Json.arr(Json.obj(
      "type" -> Json.fromString("text"),
      "text" -> Json.fromString(msg),
    )),
    "structuredContent" -> Json.obj(
      "error" -> Json.obj(
        "code"    -> Json.fromInt(code),
        "message" -> Json.fromString(msg),
      )
    ),
    "isError"           -> Json.True,
  )
}
