package izumi.test.domain02

import _root_.cats.effect.Async
import _root_.io.circe.{Json, parser}
import izumi.functional.bio.{Error2, Exit, F, IO2}
import izumi.idealingua.runtime.rpc.{
  IRTDecodingException,
  IRTMethodId,
  IRTMethodName,
  IRTMissingHandlerException,
  IRTServerMultiplexor,
  IRTServiceId,
  IRTUnathorizedRequestContextException,
}
import org.http4s.{HttpRoutes, Request, Response, Status}
import org.http4s.circe._
import org.http4s.dsl.Http4sDsl

/** MCP / HTTP4s bridge for `ImportIdService`. Generated by
  * `DomainServiceMcpRenderer` per plan §3.1. Mb1 scope: only
  * `Output.Singular` methods route to the IRT mux; others return
  * an MCP error envelope `-32601` until Mb2.
  *
  * Effect typeclasses: bifunctor `F[+_, +_]: IO2: Error2` is the
  * user-facing surface (mirrors the IRT runtime + plan D3); http4s
  * routes additionally need `cats.effect.Async[F[Throwable, _]]` at the
  * edge for its DSL (`Ok(...)`, `req.as[Json]`, etc.) — same pattern
  * `HttpServer.scala` uses.
  */
object ImportIdServiceMcpRoutes {

  /** tools/list envelope loaded from classpath resource at first access
    * (D8(b)). The translator emits `mcp/ImportIdService.mcp.json` alongside
    * this source file when `emitMcpBridge = true`.
    */
  private lazy val toolsListJson: Json = {
    val stream = getClass.getClassLoader.getResourceAsStream("mcp/ImportIdService.mcp.json")
    require(stream != null, "Missing classpath resource: mcp/ImportIdService.mcp.json")
    try parser.parse(scala.io.Source.fromInputStream(stream, "UTF-8").mkString).toTry.get
    finally stream.close()
  }

  private val toolName_some = "izumi.test.domain02.ImportIdService.some"
  private val methodId_some = IRTMethodId(IRTServiceId("ImportIdService"), IRTMethodName("some"))
  private val toolName_mixi = "izumi.test.domain02.ImportIdService.mixi"
  private val methodId_mixi = IRTMethodId(IRTServiceId("ImportIdService"), IRTMethodName("mixi"))
  private val toolName_update = "izumi.test.domain02.ImportIdService.update"
  private val methodId_update = IRTMethodId(IRTServiceId("ImportIdService"), IRTMethodName("update"))

  def routes[F[+_, +_]: IO2: Error2, C](
    mux: IRTServerMultiplexor[F, C],
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): HttpRoutes[F[Throwable, _]] = {
    import dsl._
    HttpRoutes.of[F[Throwable, _]] {
      case GET -> Root / "mcp" / "tools" / "list" =>
        Ok(toolsListJson)

      case req @ POST -> Root / "mcp" / "tools" / "call" =>
        req.as[Json].flatMap { body =>
          val nameOpt  = body.hcursor.downField("name").as[String].toOption
          val argsJson = body.hcursor.downField("arguments").as[Json].getOrElse(Json.obj())
          nameOpt match {
            case Some(`toolName_some`) =>
              call(req, argsJson, methodId_some, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_mixi`) =>
              Ok(mcpError(-32601, "method not implemented in Mb1"))
            case Some(`toolName_update`) =>
              Ok(mcpError(-32601, "method not implemented in Mb1"))
            case Some(other) if other.startsWith("izumi.test.domain02.ImportIdService.") =>
              Ok(mcpError(-32601, s"Method not found: $other"))
            case _ =>
              NotFound()
          }
        }
    }
  }

  private def call[F[+_, +_]: IO2: Error2, C](
    req: Request[F[Throwable, _]],
    args: Json,
    methodId: IRTMethodId,
    wrap: Boolean,
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    mux: IRTServerMultiplexor[F, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): F[Throwable, Response[F[Throwable, _]]] = {
    import dsl._
    (for {
      ctx <- extractCtx(req)
      raw <- mux.invokeMethod(methodId)(ctx, args)
    } yield {
      val shaped = if (wrap) Json.obj("result" -> raw) else raw
      Json.obj(
        "content" -> Json.arr(Json.obj(
          "type" -> Json.fromString("text"),
          "text" -> Json.fromString(shaped.noSpaces),
        )),
        "structuredContent" -> shaped,
        "isError"           -> Json.False,
      )
    }).sandboxExit.flatMap {
      case Exit.Success(j)                                          => Ok(j)
      case Exit.Error(_: IRTMissingHandlerException, _)             => Ok(mcpError(-32601, "Method not found"))
      case Exit.Error(_: IRTDecodingException, _)                   => Ok(mcpError(-32602, "Invalid arguments"))
      case Exit.Error(_: _root_.io.circe.Error, _)                  => Ok(mcpError(-32602, "Invalid arguments"))
      case Exit.Error(_: IRTUnathorizedRequestContextException, _)  => F.pure(Response[F[Throwable, _]](status = Status.Unauthorized))
      case _                                                        => Ok(mcpError(-32603, "Internal error"))
    }
  }

  private def mcpError(code: Int, msg: String): Json = Json.obj(
    "content"           -> Json.arr(Json.obj(
      "type" -> Json.fromString("text"),
      "text" -> Json.fromString(msg),
    )),
    "structuredContent" -> Json.obj(
      "error" -> Json.obj(
        "code"    -> Json.fromInt(code),
        "message" -> Json.fromString(msg),
      )
    ),
    "isError"           -> Json.True,
  )
}
