package mcpdemo

import _root_.cats.effect.Async
import _root_.io.circe.{Json, parser}
import izumi.functional.bio.{Error2, Exit, IO2}
import izumi.idealingua.runtime.rpc.{
  IRTDecodingException,
  IRTGenericFailure,
  IRTLimitReachedException,
  IRTMethodId,
  IRTMethodName,
  IRTMissingHandlerException,
  IRTServerMultiplexor,
  IRTServiceId,
  IRTTypeMismatchException,
  IRTUnathorizedRequestContextException,
  IRTUnparseableDataException,
}
import org.http4s.{HttpRoutes, Request, Response}
import org.http4s.circe._
import org.http4s.dsl.Http4sDsl

/** MCP / HTTP4s bridge for `Shapes`. Generated by
  * `DomainServiceMcpRenderer` per plan §3.1. Mb2 scope: all 5
  * `Output` variants (Void / Singular / Struct / Algebraic /
  * Alternative) dispatch uniformly through `mux.invokeMethod` per
  * plan D5; the static `wrap` flag is derived from
  * `OutputWrapPolicy.isWrapped` (§3.2).
  *
  * Effect typeclasses: bifunctor `F[+_, +_]: IO2: Error2` is the
  * user-facing surface (mirrors the IRT runtime + plan D3); http4s
  * routes additionally need `cats.effect.Async[F[Throwable, _]]` at the
  * edge for its DSL (`Ok(...)`, `req.as[Json]`, etc.) — same pattern
  * `HttpServer.scala` uses.
  */
object ShapesMcpRoutes {

  /** tools/list envelope loaded from classpath resource at first access
    * (D8(b)). The translator emits `mcp/Shapes.mcp.json` alongside
    * this source file when `emitMcpBridge = true`.
    */
  private lazy val toolsListJson: Json = {
    val stream = getClass.getClassLoader.getResourceAsStream("mcp/Shapes.mcp.json")
    require(stream != null, "Missing classpath resource: mcp/Shapes.mcp.json")
    try parser.parse(scala.io.Source.fromInputStream(stream, "UTF-8").mkString).toTry.get
    finally stream.close()
  }

  private val toolName_ping = "mcpdemo.Shapes.ping"
  private val methodId_ping = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("ping"))
  private val toolName_upper = "mcpdemo.Shapes.upper"
  private val methodId_upper = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("upper"))
  private val toolName_add = "mcpdemo.Shapes.add"
  private val methodId_add = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("add"))
  private val toolName_echo = "mcpdemo.Shapes.echo"
  private val methodId_echo = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("echo"))
  private val toolName_divmod = "mcpdemo.Shapes.divmod"
  private val methodId_divmod = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("divmod"))
  private val toolName_reverse = "mcpdemo.Shapes.reverse"
  private val methodId_reverse = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("reverse"))
  private val toolName_invertMap = "mcpdemo.Shapes.invertMap"
  private val methodId_invertMap = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("invertMap"))
  private val toolName_maybeUpper = "mcpdemo.Shapes.maybeUpper"
  private val methodId_maybeUpper = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("maybeUpper"))
  private val toolName_nextColor = "mcpdemo.Shapes.nextColor"
  private val methodId_nextColor = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("nextColor"))
  private val toolName_makeProfile = "mcpdemo.Shapes.makeProfile"
  private val methodId_makeProfile = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("makeProfile"))
  private val toolName_pay = "mcpdemo.Shapes.pay"
  private val methodId_pay = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("pay"))
  private val toolName_divideSafe = "mcpdemo.Shapes.divideSafe"
  private val methodId_divideSafe = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("divideSafe"))
  private val toolName_noteValue = "mcpdemo.Shapes.noteValue"
  private val methodId_noteValue = IRTMethodId(IRTServiceId("Shapes"), IRTMethodName("noteValue"))

  def routes[F[+_, +_]: IO2: Error2, C](
    mux: IRTServerMultiplexor[F, C],
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): HttpRoutes[F[Throwable, _]] = {
    import dsl._
    HttpRoutes.of[F[Throwable, _]] {
      case GET -> Root / "mcp" / "tools" / "list" =>
        Ok(toolsListJson)

      case req @ POST -> Root / "mcp" / "tools" / "call" =>
        req.as[Json].flatMap { body =>
          val nameOpt  = body.hcursor.downField("name").as[String].toOption
          val argsJson = body.hcursor.downField("arguments").as[Json].getOrElse(Json.obj())
          nameOpt match {
            case Some(`toolName_ping`) =>
              call(req, argsJson, methodId_ping, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_upper`) =>
              call(req, argsJson, methodId_upper, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_add`) =>
              call(req, argsJson, methodId_add, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_echo`) =>
              call(req, argsJson, methodId_echo, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_divmod`) =>
              call(req, argsJson, methodId_divmod, wrap = false, extractCtx, mux, dsl)
            case Some(`toolName_reverse`) =>
              call(req, argsJson, methodId_reverse, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_invertMap`) =>
              call(req, argsJson, methodId_invertMap, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_maybeUpper`) =>
              call(req, argsJson, methodId_maybeUpper, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_nextColor`) =>
              call(req, argsJson, methodId_nextColor, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_makeProfile`) =>
              call(req, argsJson, methodId_makeProfile, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_pay`) =>
              call(req, argsJson, methodId_pay, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_divideSafe`) =>
              call(req, argsJson, methodId_divideSafe, wrap = true, extractCtx, mux, dsl)
            case Some(`toolName_noteValue`) =>
              call(req, argsJson, methodId_noteValue, wrap = true, extractCtx, mux, dsl)
            case Some(other) if other.startsWith("mcpdemo.Shapes.") =>
              Ok(mcpError(-32601, s"Method not found: $other"))
            case _ =>
              NotFound()
          }
        }
    }
  }

  private def call[F[+_, +_]: IO2: Error2, C](
    req: Request[F[Throwable, _]],
    args: Json,
    methodId: IRTMethodId,
    wrap: Boolean,
    extractCtx: Request[F[Throwable, _]] => F[Throwable, C],
    mux: IRTServerMultiplexor[F, C],
    dsl: Http4sDsl[F[Throwable, _]],
  )(implicit AT: Async[F[Throwable, _]]
  ): F[Throwable, Response[F[Throwable, _]]] = {
    import dsl._
    (for {
      ctx <- extractCtx(req)
      raw <- mux.invokeMethod(methodId)(ctx, args)
    } yield {
      val shaped = if (wrap) Json.obj("result" -> raw) else raw
      Json.obj(
        "content" -> Json.arr(Json.obj(
          "type" -> Json.fromString("text"),
          "text" -> Json.fromString(shaped.noSpaces),
        )),
        "structuredContent" -> shaped,
        "isError"           -> Json.False,
      )
    }).sandboxExit.flatMap {
      // Plan §9 mapping: IRT semantic failures surface in-band as MCP
      // `isError:true` envelopes (HTTP 200). Out-of-band HTTP statuses
      // are reserved for transport-layer failures (malformed body,
      // route mismatch, unhandled middleware exception) — those are
      // already produced by http4s before this `call` runs.
      // Codes follow JSON-RPC 2.0 reserved range: -32700 parse,
      // -32601 method-not-found, -32602 invalid-params, -32603 internal,
      // -32000..-32099 server-defined (rate-limit, unauthorized).
      // Diverges from `HttpServer.handleHttpResult` (HTTP 401, 429) per
      // plan §9: MCP semantics treat auth + rate-limit as tool-level
      // failures, not transport-level.
      // Underlying `getMessage` is surfaced for decoding errors; we
      // deliberately do NOT surface stack traces or causes (avoid
      // leaking server internals).
      case Exit.Success(j) => Ok(j)
      case Exit.Error(_: IRTMissingHandlerException, _) =>
        Ok(mcpError(-32601, s"Method not found: ${methodId.service.value}.${methodId.methodId.value}"))
      case Exit.Error(e: IRTUnparseableDataException, _) =>
        Ok(mcpError(-32700, s"Parse error: ${safeMsg(e)}"))
      case Exit.Error(e: IRTTypeMismatchException, _) =>
        Ok(mcpError(-32602, s"Invalid arguments (type mismatch): ${safeMsg(e)}"))
      case Exit.Error(e: IRTDecodingException, _) =>
        Ok(mcpError(-32602, s"Invalid arguments: ${safeMsg(e)}"))
      case Exit.Error(e: _root_.io.circe.Error, _) =>
        Ok(mcpError(-32602, s"Invalid arguments: ${safeMsg(e)}"))
      case Exit.Error(e: IRTLimitReachedException, _) =>
        Ok(mcpError(-32000, s"Rate limit exceeded: ${safeMsg(e)}"))
      case Exit.Error(_: IRTUnathorizedRequestContextException, _) =>
        Ok(mcpError(-32001, "Unauthorized"))
      case Exit.Error(_: IRTGenericFailure, _) =>
        Ok(mcpError(-32603, "Internal error"))
      case _ =>
        Ok(mcpError(-32603, "Internal error"))
    }
  }

  /** Surface the exception's own message only — never the cause chain
    * or stack trace — and fall back to the class name if `getMessage`
    * is `null`. Prevents leaking server internals (file paths,
    * library-version strings, host names) into the MCP envelope.
    */
  private def safeMsg(t: Throwable): String = {
    val m = t.getMessage
    if (m == null) t.getClass.getSimpleName else m
  }

  private def mcpError(code: Int, msg: String): Json = Json.obj(
    "content"           -> Json.arr(Json.obj(
      "type" -> Json.fromString("text"),
      "text" -> Json.fromString(msg),
    )),
    "structuredContent" -> Json.obj(
      "error" -> Json.obj(
        "code"    -> Json.fromInt(code),
        "message" -> Json.fromString(msg),
      )
    ),
    "isError"           -> Json.True,
  )
}
