package izumi.idealingua.runtime.rpc.http4s

import scala.annotation.nowarn
import scala.concurrent.duration._

import io.circe.Json
import izumi.functional.bio.Exit
import izumi.idealingua.runtime.rpc.{IRTOutputMiddleware, IRTServerMultiplexor}
import mcpdemo.{ShapesMcpRoutes, ShapesServer, ShapesServerImpl, ShapesWrappedServer}
import org.http4s.{EntityDecoder, EntityEncoder, Method, Request, Status, Uri}
import org.http4s.blaze.server.BlazeServerBuilder
import org.http4s.circe._
import org.http4s.dsl.Http4sDsl
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.server.Server
import org.scalatest.wordspec.AnyWordSpec

/** Mb4-B integration spec: every `Shapes` MCP tool reached over a real HTTP
  * socket via `BlazeServerBuilder` + `EmberClientBuilder`, exercising every
  * `DefMethod.Output` shape (Void / Singular primitive / Singular DTO /
  * Struct / Algebraic / Alternative-Singular / Alternative-Void) and a
  * range of input shapes (empty / primitive / multi-primitive / DTO /
  * `list[T]` / `map[K,V]` / `opt[T]` / `enum`).
  *
  * Fixtures generated by idlc from `src/test/resources/mcpdemo-idl/` with
  * `emitMcpBridge=true`, copied verbatim under `src/test/scala/mcpdemo/`
  * and `src/test/resources/mcp/`.
  *
  * Wrap policy observed on the wire (per `OutputWrapPolicy.isWrapped`):
  *   - Singular (any inner type)  → `structuredContent = { "result": <raw> }`.
  *   - Void / Struct / Algebraic / Alternative → `structuredContent = <raw>`
  *     (no `result` wrap; the IRT output codec already produces a JSON
  *     object).
  */
@nowarn("msg=unused value of type org.scalatest.compatible.Assertion")
final class McpBridgeRealServerSpec extends AnyWordSpec {

  type BIO[+E, +A] = zio.IO[E, A]

  implicit val unsafeRun: izumi.functional.bio.UnsafeRun2[BIO]      = Http4sTransportTest.IO2R
  implicit val io2: izumi.functional.bio.IO2[BIO]                   = izumi.functional.bio.impl.AsyncZio
  implicit val async2: izumi.functional.bio.Async2[BIO]             = izumi.functional.bio.impl.AsyncZio
  implicit val asyncThrowable: cats.effect.Async[BIO[Throwable, *]] = zio.interop.catz.asyncInstance

  private val dsl: Http4sDsl[BIO[Throwable, *]] = Http4sDsl.apply[BIO[Throwable, *]]

  private val realService: ShapesServer[BIO, Unit] = new ShapesServerImpl[BIO, Unit]
  private val mux: IRTServerMultiplexor[BIO, Unit] =
    new IRTServerMultiplexor.FromServices[BIO, Unit](
      Set(new ShapesWrappedServer[BIO, Unit](realService)),
      IRTOutputMiddleware.empty[BIO, Unit],
    )

  private val extractUnit: Request[BIO[Throwable, *]] => BIO[Throwable, Unit] =
    _ => izumi.functional.bio.F.pure(())

  private val routes = ShapesMcpRoutes.routes[BIO, Unit](mux, extractUnit, dsl)

  private def runUnsafe[A](io: BIO[Throwable, A]): A =
    unsafeRun.unsafeRunSync(io) match {
      case Exit.Success(v)             => v
      case f: Exit.Failure[?] @unchecked => throw f.trace.toThrowable
    }

  private def withServer[A](body: Uri => A): A = {
    val resource: cats.effect.Resource[BIO[Throwable, *], Server] =
      BlazeServerBuilder[BIO[Throwable, *]]
        .bindHttp(0, "127.0.0.1")
        .withHttpApp(routes.orNotFound)
        .resource
    runUnsafe(resource.use { srv =>
      val base = Uri.unsafeFromString(s"http://127.0.0.1:${srv.address.getPort}")
      izumi.functional.bio.F.syncThrowable(body(base))
    })
  }

  private def client[A](body: org.http4s.client.Client[BIO[Throwable, *]] => BIO[Throwable, A]): A =
    runUnsafe {
      EmberClientBuilder
        .default[BIO[Throwable, *]]
        .withTimeout(5.seconds)
        .build
        .use(body)
    }

  private def post(uri: Uri, body: Json): (Status, Json) = {
    implicit val je: EntityEncoder[BIO[Throwable, *], Json] = jsonEncoderOf[BIO[Throwable, *], Json]
    implicit val jd: EntityDecoder[BIO[Throwable, *], Json] = jsonDecoder[BIO[Throwable, *]]
    val req = Request[BIO[Throwable, *]](Method.POST, uri).withEntity(body)
    client(c => c.run(req).use(resp => resp.as[Json].map(j => (resp.status, j))))
  }

  private def get(uri: Uri): (Status, Json) = {
    implicit val jd: EntityDecoder[BIO[Throwable, *], Json] = jsonDecoder[BIO[Throwable, *]]
    val req = Request[BIO[Throwable, *]](Method.GET, uri)
    client(c => c.run(req).use(resp => resp.as[Json].map(j => (resp.status, j))))
  }

  private def callBody(toolName: String, args: Json): Json =
    Json.obj("name" -> Json.fromString(toolName), "arguments" -> args)

  // Successful envelope → structuredContent. Singular outputs sit under .result;
  // non-Singular outputs (Void/Struct/Algebraic/Alternative) are the
  // structuredContent itself.
  private def assertOk(status: Status, body: Json): Json = {
    assert(status == Status.Ok, s"expected 200, got $status; body=$body")
    val isError = body.hcursor.get[Boolean]("isError").toOption
    assert(isError.contains(false), s"expected isError:false, got $body")
    body.hcursor.downField("structuredContent").focus.getOrElse(throw new AssertionError(s"missing structuredContent: $body"))
  }

  // Singular outputs: pull the `result` field. Other shapes: return sc as-is.
  private def resultOf(sc: Json): Json =
    sc.hcursor.downField("result").focus.getOrElse(sc)

  private val tool = "mcpdemo.Shapes."

  "MCP bridge over real Blaze socket" should {
    "tools/list returns all 13 tools" in withServer { base =>
      val (status, body) = get(base / "mcp" / "tools" / "list")
      assert(status == Status.Ok)
      val tools = body.hcursor.downField("tools").focus.flatMap(_.asArray).getOrElse(fail("missing tools[]"))
      val names = tools.flatMap(_.hcursor.get[String]("name").toOption).toSet
      val expected = Set(
        "ping", "upper", "add", "echo", "divmod", "reverse", "invertMap",
        "maybeUpper", "nextColor", "makeProfile", "pay", "divideSafe", "noteValue",
      ).map(tool + _)
      assert(names == expected, s"missing/unexpected tools — got $names")
    }

    "ping (Void output)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "ping", Json.obj())))
      // Void carries no payload; the IRT codec emits an empty object {}.
      assert(sc == Json.obj(), s"expected {}, got $sc")
    }

    "upper (Singular str)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "upper", Json.obj("s" -> Json.fromString("hello")))))
      val v  = resultOf(sc).asString.getOrElse(fail(s"expected string in $sc"))
      assert(v == "HELLO")
    }

    "add (multi-primitive in, Singular i64 out)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "add", Json.obj("a" -> Json.fromLong(7), "b" -> Json.fromLong(35)))))
      val v  = resultOf(sc).asNumber.flatMap(_.toLong).getOrElse(fail(s"expected number in $sc"))
      assert(v == 42L)
    }

    "echo (DTO in, DTO out)" in withServer { base =>
      val args = Json.obj("req" -> Json.obj("msg" -> Json.fromString("hi"), "n" -> Json.fromInt(3)))
      val sc   = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "echo", args)))
      val r    = resultOf(sc)
      assert(r.hcursor.get[String]("echo").toOption.contains("hi"), s"echo: $r")
      assert(r.hcursor.get[Int]("count").toOption.contains(3),       s"count: $r")
    }

    "divmod (Struct out — no .result wrap)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "divmod", Json.obj("a" -> Json.fromLong(17), "b" -> Json.fromLong(5)))))
      assert(sc.hcursor.get[Long]("quotient").toOption.contains(3L),  s"quotient: $sc")
      assert(sc.hcursor.get[Long]("remainder").toOption.contains(2L), s"remainder: $sc")
    }

    "reverse (list in/out)" in withServer { base =>
      val args = Json.obj("items" -> Json.arr(Json.fromString("a"), Json.fromString("b"), Json.fromString("c")))
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "reverse", args)))
      val v = resultOf(sc).asArray.map(_.flatMap(_.asString).toList).getOrElse(fail(s"expected array in $sc"))
      assert(v == List("c", "b", "a"))
    }

    "invertMap (map in/out)" in withServer { base =>
      val args = Json.obj("m" -> Json.obj("k1" -> Json.fromString("v1"), "k2" -> Json.fromString("v2")))
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "invertMap", args)))
      val v = resultOf(sc).as[Map[String, String]].toOption.getOrElse(fail(s"expected map in $sc"))
      assert(v == Map("v1" -> "k1", "v2" -> "k2"))
    }

    "maybeUpper Some (opt in/out)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "maybeUpper", Json.obj("s" -> Json.fromString("ok")))))
      val r  = resultOf(sc)
      assert(r.asString.contains("OK"), s"expected 'OK', got $r")
    }

    "maybeUpper None (opt None in)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "maybeUpper", Json.obj())))
      val r  = resultOf(sc)
      assert(r == Json.Null, s"expected null, got $r")
    }

    "nextColor (enum in, Singular DTO out)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "nextColor", Json.obj("c" -> Json.fromString("Red")))))
      val r  = resultOf(sc)
      assert(r.hcursor.get[String]("color").toOption.contains("Green"), s"color: $r")
    }

    "makeProfile (multi-arg in incl enum, Singular DTO out)" in withServer { base =>
      val args = Json.obj(
        "name"  -> Json.fromString("alice"),
        "age"   -> Json.fromInt(30),
        "color" -> Json.fromString("Blue"),
      )
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "makeProfile", args)))
      val r  = resultOf(sc)
      assert(r.hcursor.get[String]("name").toOption.contains("alice"))
      assert(r.hcursor.get[Int]("age").toOption.contains(30))
      assert(r.hcursor.get[String]("color").toOption.contains("Blue"))
    }

    "pay (Algebraic out — PaymentOk branch)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "pay", Json.obj("amount" -> Json.fromLong(100)))))
      // Algebraic wrapper IS singular (the ADT is a single value) → wrap=true:
      //   structuredContent.result = { "PaymentOk": { ... } }.
      val r  = resultOf(sc)
      val ok = r.hcursor.downField("PaymentOk").focus.getOrElse(fail(s"expected PaymentOk branch in $r"))
      assert(ok.hcursor.get[Long]("amount").toOption.contains(100L))
      assert(ok.hcursor.get[String]("txId").toOption.contains("tx-100"))
    }

    "pay (Algebraic out — PaymentRejected branch)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "pay", Json.obj("amount" -> Json.fromLong(-5)))))
      val r   = resultOf(sc)
      val rej = r.hcursor.downField("PaymentRejected").focus.getOrElse(fail(s"expected PaymentRejected branch in $r"))
      assert(rej.hcursor.get[Int]("code").toOption.contains(422))
    }

    "divideSafe (Alternative Singular!!Singular — success)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "divideSafe", Json.obj("a" -> Json.fromLong(10), "b" -> Json.fromLong(2)))))
      // Alternative output ADT tagged: { "Success": { ... } } | { "Failure": { ... } }.
      val raw = sc.spaces2
      assert(raw.contains("\"Success\""), s"expected Success branch in $sc")
      assert(raw.contains("5"),           s"expected the quotient 5 in $sc")
    }

    "divideSafe (Alternative Singular!!Singular — failure)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "divideSafe", Json.obj("a" -> Json.fromLong(1), "b" -> Json.fromLong(0)))))
      val raw = sc.spaces2
      assert(raw.contains("\"Failure\""), s"expected Failure branch in $sc")
      assert(raw.contains("division by zero"), s"expected fail msg in $sc")
    }

    "noteValue (Alternative Void!!Singular — success)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "noteValue", Json.obj("v" -> Json.fromInt(7)))))
      val raw = sc.spaces2
      assert(raw.contains("\"Success\""), s"expected Success branch in $sc")
    }

    "noteValue (Alternative Void!!Singular — failure)" in withServer { base =>
      val sc = assertOk.tupled(post(base / "mcp" / "tools" / "call", callBody(tool + "noteValue", Json.obj("v" -> Json.fromInt(-1)))))
      val raw = sc.spaces2
      assert(raw.contains("\"Failure\""), s"expected Failure branch in $sc")
      assert(raw.contains("negative"),    s"expected fail msg in $sc")
    }

    "every tool entry exposes inputSchema and outputSchema" in withServer { base =>
      val (_, body) = get(base / "mcp" / "tools" / "list")
      val tools = body.hcursor.downField("tools").focus.flatMap(_.asArray).getOrElse(fail("missing tools[]"))
      tools.foreach { t =>
        val name = t.hcursor.get[String]("name").toOption.getOrElse(fail("nameless tool"))
        assert(t.hcursor.downField("inputSchema").focus.isDefined,  s"tool $name missing inputSchema")
        assert(t.hcursor.downField("outputSchema").focus.isDefined, s"tool $name missing outputSchema")
      }
    }

    "unknown method returns -32601 in-band" in withServer { base =>
      val (status, body) = post(base / "mcp" / "tools" / "call", callBody(tool + "doesNotExist", Json.obj()))
      assert(status == Status.Ok)
      assert(body.hcursor.get[Boolean]("isError").toOption.contains(true))
      val code = body.hcursor.downField("structuredContent").downField("error").get[Int]("code").toOption
      assert(code.contains(-32601), s"expected -32601, got $code")
    }
  }
}
