// Auto-generated by debug/20260514-192000-gen-ts-sample.py for the R3b regression-harness
// sample-app cycle. Covers every user-declared type the `:typescript` translator exports
// over the full main-tests corpus.
//
// REGRESSION-GATE NOTE: TypeScript-generated DTOs use object-literal construction
// `new <Cls>(<NameSerialized>)` — NOT positional like Scala/C#. Field-order changes still
// surface as a TSC compile error because the Serialized interface field set is checked.
// The R3 brief documents this with `# x-skip-positional` lines.
//
// SKIPPED wireIds (service/buzzer method input/output ephemerals — not exported in the
// generated TS tree; the marshaller dispatches input/output payloads directly and never
// references these by wireId at runtime):
//   # x-skip-positional  coverage.buzzers.allbouts.AllOutputsBuzzer.AlgebraicEventInput\tdefault  (service/buzzer ephemeral not exported in TS)
//   # x-skip-positional  coverage.buzzers.allbouts.AllOutputsBuzzer.AlgebraicEventOutput\tBuzzerErr  (service/buzzer ephemeral not exported in TS)
//   # x-skip-positional  coverage.buzzers.allbouts.AllOutputsBuzzer.AlgebraicEventOutput\tBuzzerOk  (service/buzzer ephemeral not exported in TS)
//   # x-skip-positional  coverage.buzzers.allbouts.AllOutputsBuzzer.AlternativeEventInput\tdefault  (service/buzzer ephemeral not exported in TS)
//   # x-skip-positional  coverage.buzzers.allbouts.AllOutputsBuzzer.AlternativeEventOutput\tFailure  (service/buzzer ephemeral not exported in TS)
//   # x-skip-positional  ... (155 total skipped — full list at bottom)

import { AFaceStruct } from './idltest/algebraics/AFace';
import { AdtTestID } from './idltest/algebraics/AdtTestID';
import { ComplexAdt } from './idltest/algebraics/ComplexAdt';
import { ComplexAdt2 } from './idltest/algebraics/ComplexAdt2';
import { Failure } from './idltest/algebraics/Failure';
import { Success } from './idltest/algebraics/Success';
import { D1 } from './idltest/aliases/D1';
import { M1Struct } from './idltest/aliases/M1';
import { M2Struct as M2Struct__idltest_aliases2_M2 } from './idltest/aliases2/M2';
import { RecordId } from './idltest/anyvals/RecordId';
import { SimpleAnyValRecord } from './idltest/anyvals/SimpleAnyValRecord';
import { Test00Data1AnyVal } from './idltest/anyvals/Test00Data1AnyVal';
import { Test00Data2AnyVal } from './idltest/anyvals/Test00Data2AnyVal';
import { Test01DataAnyVal1 } from './idltest/anyvals/Test01DataAnyVal1';
import { Test01DataAnyVal2 } from './idltest/anyvals/Test01DataAnyVal2';
import { Test01MixinAnyValStruct } from './idltest/anyvals/Test01MixinAnyVal';
import { Test02DtoAnyVal } from './idltest/anyvals/Test02DtoAnyVal';
import { Test02UserAnyVal } from './idltest/anyvals/Test02UserAnyVal';
import { WithRecordIdStruct } from './idltest/anyvals/WithRecordId';
import { BoolNodeStruct } from './idltest/ast/BoolNode';
import { EventData } from './idltest/ast/EventData';
import { FloatNodeStruct } from './idltest/ast/FloatNode';
import { IntNodeStruct } from './idltest/ast/IntNode';
import { PublicData } from './idltest/ast/PublicData';
import { SymNodeStruct } from './idltest/ast/SymNode';
import { TBoolNodeStruct } from './idltest/ast/TBoolNode';
import { TFloatNodeStruct } from './idltest/ast/TFloatNode';
import { TIntNodeStruct } from './idltest/ast/TIntNode';
import { TSymNodeStruct } from './idltest/ast/TSymNode';
import { Type } from './idltest/ast/Type';
import { TypeInfoStruct } from './idltest/ast/TypeInfo';
import { M0Struct } from './idltest/clones/M0';
import { M2Struct as M2Struct__idltest_clones_M2 } from './idltest/clones/M2';
import { TestPair } from './idltest/consts/TestPair';
import { ParameterDTO } from './idltest/datainheritance/ParameterDTO';
import { TestData1 } from './idltest/datainheritance/TestData1';
import { TestData2 } from './idltest/datainheritance/TestData2';
import { UserDTO } from './idltest/datainheritance/UserDTO';
import { DTO1 as DTO1__idltest_diamonds_DTO1 } from './idltest/diamonds/DTO1';
import { TestInterface1Struct as TestInterface1Struct__idltest_diamonds_TestInterface1 } from './idltest/diamonds/TestInterface1';
import { TestInterface2Struct as TestInterface2Struct__idltest_diamonds_TestInterface2 } from './idltest/diamonds/TestInterface2';
import { TestInterface3Struct as TestInterface3Struct__idltest_diamonds_TestInterface3 } from './idltest/diamonds/TestInterface3';
import { IntPairStruct as IntPairStruct__idltest_dtofields_IntPair } from './idltest/dtofields/IntPair';
import { ListObj } from './idltest/dtofields/ListObj';
import { MetadataStruct as MetadataStruct__idltest_dtofields_Metadata } from './idltest/dtofields/Metadata';
import { NullableContentStruct } from './idltest/dtofields/NullableContent';
import { NullableObj } from './idltest/dtofields/NullableObj';
import { OptionalObj } from './idltest/dtofields/OptionalObj';
import { Point as Point__idltest_dtofields_Point } from './idltest/dtofields/Point';
import { PointLikeStruct as PointLikeStruct__idltest_dtofields_PointLike } from './idltest/dtofields/PointLike';
import { WHPairStruct } from './idltest/dtofields/WHPair';
import { EnumHolder } from './idltest/enums/EnumHolder';
import { KVEnumGeneric } from './idltest/enums/KVEnumGeneric';
import { BranchA } from './idltest/events/BranchA';
import { BranchB } from './idltest/events/BranchB';
import { BucketID } from './idltest/identifiers/BucketID';
import { CompanyId } from './idltest/identifiers/CompanyId';
import { ComplexID } from './idltest/identifiers/ComplexID';
import { KVIDGeneric } from './idltest/identifiers/KVIDGeneric';
import { UserId as UserId__idltest_identifiers_UserId } from './idltest/identifiers/UserId';
import { UserWithEnumId } from './idltest/identifiers/UserWithEnumId';
import { CovariantStruct } from './idltest/inheritance/Covariant';
import { CovariantAStruct } from './idltest/inheritance/CovariantA';
import { CovariantBStruct } from './idltest/inheritance/CovariantB';
import { DataWithAB } from './idltest/inheritance/DataWithAB';
import { EmptyStruct } from './idltest/inheritance/Empty';
import { IA1Struct } from './idltest/inheritance/IA1';
import { IA2Struct } from './idltest/inheritance/IA2';
import { IntPairStruct as IntPairStruct__idltest_inheritance_IntPair } from './idltest/inheritance/IntPair';
import { MetadataStruct as MetadataStruct__idltest_inheritance_Metadata } from './idltest/inheritance/Metadata';
import { NotificationStruct } from './idltest/inheritance/Notification';
import { NotificationWithAStruct } from './idltest/inheritance/NotificationWithA';
import { NotificationWithABStruct } from './idltest/inheritance/NotificationWithAB';
import { NotificationWithBStruct } from './idltest/inheritance/NotificationWithB';
import { Point as Point__idltest_inheritance_Point } from './idltest/inheritance/Point';
import { PointLikeStruct as PointLikeStruct__idltest_inheritance_PointLike } from './idltest/inheritance/PointLike';
import { Str } from './idltest/inheritance/Str';
import { JLBool } from './idltest/json/JLBool';
import { JLNull } from './idltest/json/JLNull';
import { JLNumber } from './idltest/json/JLNumber';
import { JLString } from './idltest/json/JLString';
import { LengthInBytesStruct } from './idltest/phase/LengthInBytes';
import { NameStruct } from './idltest/phase/Name';
import { Name_incoming } from './idltest/phase/Name_incoming';
import { Name_stored } from './idltest/phase/Name_stored';
import { Name_stored_Struct } from './idltest/phase/Name_stored_';
import { ErrorDataStruct } from './idltest/services/ErrorData';
import { Package } from './idltest/services/Package';
import { RequestStruct } from './idltest/services/Request';
import { SuccessDataStruct } from './idltest/services/SuccessData';
import { SuccessDataData } from './idltest/services/SuccessDataData';
import { Nuthing } from './idltest/streams/Nuthing';
import { IdentifiedStruct } from './idltest/substraction/Identified';
import { PersonalAttributesStruct } from './idltest/substraction/PersonalAttributes';
import { PublicUser1Struct } from './idltest/substraction/PublicUser1';
import { PublicUser2 } from './idltest/substraction/PublicUser2';
import { SecurityAttributesStruct } from './idltest/substraction/SecurityAttributes';
import { User1Struct } from './idltest/substraction/User1';
import { User2 } from './idltest/substraction/User2';
import { UserId as UserId__idltest_substraction_UserId } from './idltest/substraction/UserId';
import { TestId } from './idltest/syntax/TestId';
import { TestId1 } from './idltest/syntax/TestId1';
import { TestMixinStruct } from './idltest/syntax/TestMixin';
import { IdentifiableStruct } from './idltest/upcasts/Identifiable';
import { Item } from './idltest/upcasts/Item';
import { ItemContentStruct } from './idltest/upcasts/ItemContent';
import { AnotherTestObject } from './izumi/test/domain01/AnotherTestObject';
import { AnyValTestStruct } from './izumi/test/domain01/AnyValTest';
import { BasicFailure } from './izumi/test/domain01/BasicFailure';
import { CommonFailureStruct } from './izumi/test/domain01/CommonFailure';
import { ExtendedMixinStruct } from './izumi/test/domain01/ExtendedMixin';
import { GenericFailure } from './izumi/test/domain01/GenericFailure';
import { GenericFailureDataStruct } from './izumi/test/domain01/GenericFailureData';
import { GoAliasTestStruct } from './izumi/test/domain01/GoAliasTest';
import { IDForDomain2 } from './izumi/test/domain01/IDForDomain2';
import { ImportAppId } from './izumi/test/domain01/ImportAppId';
import { NestedClass } from './izumi/test/domain01/NestedClass';
import { OffsetLimit } from './izumi/test/domain01/OffsetLimit';
import { PrivateMixinStruct } from './izumi/test/domain01/PrivateMixin';
import { PrivateMixinParentStruct } from './izumi/test/domain01/PrivateMixinParent';
import { PrivateMixinPrivateParentStruct } from './izumi/test/domain01/PrivateMixinPrivateParent';
import { PrivateTestObject } from './izumi/test/domain01/PrivateTestObject';
import { RTestMixinStruct } from './izumi/test/domain01/RTestMixin';
import { TestIdentifier } from './izumi/test/domain01/TestIdentifier';
import { TestInterfaceStruct } from './izumi/test/domain01/TestInterface';
import { TestObject } from './izumi/test/domain01/TestObject';
import { TestValIdentifier } from './izumi/test/domain01/TestValIdentifier';
import { Adt2 } from './izumi/test/domain02/Adt2';
import { AdtA1 } from './izumi/test/domain02/AdtA1';
import { AdtA2 } from './izumi/test/domain02/AdtA2';
import { AliasedUsageData } from './izumi/test/domain02/AliasedUsageData';
import { DTO1 as DTO1__izumi_test_domain02_DTO1 } from './izumi/test/domain02/DTO1';
import { Pair1Struct } from './izumi/test/domain02/Pair1';
import { Pair2Struct } from './izumi/test/domain02/Pair2';
import { TestDataWithAlias } from './izumi/test/domain02/TestDataWithAlias';
import { TestIDReturn } from './izumi/test/domain02/TestIDReturn';
import { TestInterface1Struct as TestInterface1Struct__izumi_test_domain02_TestInterface1 } from './izumi/test/domain02/TestInterface1';
import { TestInterface2Struct as TestInterface2Struct__izumi_test_domain02_TestInterface2 } from './izumi/test/domain02/TestInterface2';
import { TestInterface3Struct as TestInterface3Struct__izumi_test_domain02_TestInterface3 } from './izumi/test/domain02/TestInterface3';
import { Email } from './overlaytest/withoverlay/Email';
import { OverlayEmailAttributes } from './overlaytest/withoverlay/OverlayEmailAttributes';
import { OverlayUserAttributes } from './overlaytest/withoverlay/OverlayUserAttributes';
import { User } from './overlaytest/withoverlay/User';

function emit(wireId: string, scenario: string, json: string): void {
  console.log(wireId + '\t' + scenario + '\t' + json);
}

const out: string[] = [];

out.push("idltest.algebraics.AFace.Struct" + '\t' + "default" + '\t' + JSON.stringify(new AFaceStruct({ a: 1 }).serialize()));
out.push("idltest.algebraics.AdtTestID" + '\t' + "default" + '\t' + JSON.stringify(new AdtTestID("AdtTestID#s1").serialize()));
out.push("idltest.algebraics.AdtTester" + '\t' + "ComplexAdt" + '\t' + JSON.stringify(({ "ComplexAdt": { id: "AdtTestID#s1" } })));
out.push("idltest.algebraics.AdtTester" + '\t' + "ComplexAdt2" + '\t' + JSON.stringify(({ "ComplexAdt2": { id: "AdtTestID#s1" } })));
out.push("idltest.algebraics.AdtWithInterface" + '\t' + "AFace" + '\t' + JSON.stringify(({ "AFace": { a: 1 } })));
out.push("idltest.algebraics.AdtWithInterface" + '\t' + "Success" + '\t' + JSON.stringify(({ "Success": { message: "s1" } })));
out.push("idltest.algebraics.Alternative" + '\t' + "Failure" + '\t' + JSON.stringify(({ "Failure": { code: 1 } })));
out.push("idltest.algebraics.Alternative" + '\t' + "TestSuccess" + '\t' + JSON.stringify(({ "TestSuccess": { message: "s1" } })));
out.push("idltest.algebraics.ComplexAdt" + '\t' + "default" + '\t' + JSON.stringify(new ComplexAdt({ id: "AdtTestID#s1" }).serialize()));
out.push("idltest.algebraics.ComplexAdt2" + '\t' + "default" + '\t' + JSON.stringify(new ComplexAdt2({ id: "AdtTestID#s1" }).serialize()));
out.push("idltest.algebraics.Failure" + '\t' + "default" + '\t' + JSON.stringify(new Failure({ code: 1 }).serialize()));
out.push("idltest.algebraics.ShortSyntax" + '\t' + "Failure" + '\t' + JSON.stringify(({ "Failure": { code: 1 } })));
out.push("idltest.algebraics.ShortSyntax" + '\t' + "TestSuccess" + '\t' + JSON.stringify(({ "TestSuccess": { message: "s1" } })));
out.push("idltest.algebraics.Success" + '\t' + "default" + '\t' + JSON.stringify(new Success({ message: "s1" }).serialize()));
out.push("idltest.aliases.D1" + '\t' + "default" + '\t' + JSON.stringify(new D1({ value: "s1", f2: "s1" }).serialize()));
out.push("idltest.aliases.M1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new M1Struct({ value: "s1" }).serialize()));
out.push("idltest.aliases2.M2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new M2Struct__idltest_aliases2_M2({ f2: "s1" }).serialize()));
out.push("idltest.anyvals.RecordId" + '\t' + "default" + '\t' + JSON.stringify(new RecordId("RecordId#3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.anyvals.SimpleAnyValRecord" + '\t' + "default" + '\t' + JSON.stringify(new SimpleAnyValRecord({ value: "s1" }).serialize()));
out.push("idltest.anyvals.Test00Data1AnyVal" + '\t' + "default" + '\t' + JSON.stringify(new Test00Data1AnyVal({ value: "s1" }).serialize()));
out.push("idltest.anyvals.Test00Data2AnyVal" + '\t' + "default" + '\t' + JSON.stringify(new Test00Data2AnyVal({ value: "s1", someInt: 1 }).serialize()));
out.push("idltest.anyvals.Test01DataAnyVal1" + '\t' + "default" + '\t' + JSON.stringify(new Test01DataAnyVal1({ value: "s1", someInt: 1 }).serialize()));
out.push("idltest.anyvals.Test01DataAnyVal2" + '\t' + "default" + '\t' + JSON.stringify(new Test01DataAnyVal2({ value: "s1", someInt: 1 }).serialize()));
out.push("idltest.anyvals.Test01MixinAnyVal.Struct" + '\t' + "default" + '\t' + JSON.stringify(new Test01MixinAnyValStruct({ value: "s1" }).serialize()));
out.push("idltest.anyvals.Test02DtoAnyVal" + '\t' + "default" + '\t' + JSON.stringify(new Test02DtoAnyVal({ value: "s1" }).serialize()));
out.push("idltest.anyvals.Test02UserAnyVal" + '\t' + "default" + '\t' + JSON.stringify(new Test02UserAnyVal({ test02DtoAnyVal: { value: "s1" }, i08: 1 }).serialize()));
out.push("idltest.anyvals.WithRecordId.Struct" + '\t' + "default" + '\t' + JSON.stringify(new WithRecordIdStruct({ id: "RecordId#3a7f0c12-1234-5678-9abc-fedcba987654" }).serialize()));
out.push("idltest.ast.AST" + '\t' + "AppNode" + '\t' + JSON.stringify(({ "AppNode": { fun: { "IntNode": { lit: 1 } }, args: [{ "IntNode": { lit: 1 } }] } })));
out.push("idltest.ast.AST" + '\t' + "BoolNode" + '\t' + JSON.stringify(({ "BoolNode": { lit: true } })));
out.push("idltest.ast.AST" + '\t' + "FloatRenamed" + '\t' + JSON.stringify(({ "FloatRenamed": { lit: 1.5 } })));
out.push("idltest.ast.AST" + '\t' + "IfNode" + '\t' + JSON.stringify(({ "IfNode": { cond: { "IntNode": { lit: 1 } }, thenNode: { "IntNode": { lit: 1 } }, elseNode: { "IntNode": { lit: 1 } } } })));
out.push("idltest.ast.AST" + '\t' + "IntNode" + '\t' + JSON.stringify(({ "IntNode": { lit: 1 } })));
out.push("idltest.ast.AST" + '\t' + "LamNode" + '\t' + JSON.stringify(({ "LamNode": { paramNames: ["s1"], body: { "IntNode": { lit: 1 } } } })));
out.push("idltest.ast.AST" + '\t' + "SymNode" + '\t' + JSON.stringify(({ "SymNode": { lit: "s1" } })));
out.push("idltest.ast.AliasedAdt" + '\t' + "Event" + '\t' + JSON.stringify(({ "Event": {  } })));
out.push("idltest.ast.AliasedAdt" + '\t' + "Public" + '\t' + JSON.stringify(({ "Public": {  } })));
out.push("idltest.ast.BoolNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new BoolNodeStruct({ lit: true }).serialize()));
out.push("idltest.ast.EventData" + '\t' + "default" + '\t' + JSON.stringify(new EventData({  }).serialize()));
out.push("idltest.ast.FloatNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new FloatNodeStruct({ lit: 1.5 }).serialize()));
out.push("idltest.ast.IntNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IntNodeStruct({ lit: 1 }).serialize()));
out.push("idltest.ast.PublicData" + '\t' + "default" + '\t' + JSON.stringify(new PublicData({  }).serialize()));
out.push("idltest.ast.SymNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new SymNodeStruct({ lit: "s1" }).serialize()));
out.push("idltest.ast.TBoolNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TBoolNodeStruct({ tpe: { label: "s1" }, lit: true }).serialize()));
out.push("idltest.ast.TFloatNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TFloatNodeStruct({ tpe: { label: "s1" }, lit: 1.5 }).serialize()));
out.push("idltest.ast.TIntNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TIntNodeStruct({ tpe: { label: "s1" }, lit: 1 }).serialize()));
out.push("idltest.ast.TSymNode.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TSymNodeStruct({ tpe: { label: "s1" }, lit: "s1" }).serialize()));
out.push("idltest.ast.Type" + '\t' + "default" + '\t' + JSON.stringify(new Type({ label: "s1" }).serialize()));
out.push("idltest.ast.TypeInfo.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TypeInfoStruct({ tpe: { label: "s1" } }).serialize()));
out.push("idltest.ast.TypedAst" + '\t' + "TAppNode" + '\t' + JSON.stringify(({ "TAppNode": { tpe: { label: "s1" }, fun: { "IntNode": { lit: 1 } }, args: [{ "IntNode": { lit: 1 } }] } })));
out.push("idltest.ast.TypedAst" + '\t' + "TBoolNode" + '\t' + JSON.stringify(({ "TBoolNode": { tpe: { label: "s1" }, lit: true } })));
out.push("idltest.ast.TypedAst" + '\t' + "TFloatNode" + '\t' + JSON.stringify(({ "TFloatNode": { tpe: { label: "s1" }, lit: 1.5 } })));
out.push("idltest.ast.TypedAst" + '\t' + "TIfNode" + '\t' + JSON.stringify(({ "TIfNode": { tpe: { label: "s1" }, cond: { "IntNode": { lit: 1 } }, thenNode: { "IntNode": { lit: 1 } }, elseNode: { "IntNode": { lit: 1 } } } })));
out.push("idltest.ast.TypedAst" + '\t' + "TIntNode" + '\t' + JSON.stringify(({ "TIntNode": { tpe: { label: "s1" }, lit: 1 } })));
out.push("idltest.ast.TypedAst" + '\t' + "TLamNode" + '\t' + JSON.stringify(({ "TLamNode": { tpe: { label: "s1" }, paramNames: ["s1"], body: { "IntNode": { lit: 1 } } } })));
out.push("idltest.ast.TypedAst" + '\t' + "TSymNode" + '\t' + JSON.stringify(({ "TSymNode": { tpe: { label: "s1" }, lit: "s1" } })));
out.push("idltest.clones.M0.Struct" + '\t' + "default" + '\t' + JSON.stringify(new M0Struct({ value: "s1" }).serialize()));
out.push("idltest.clones.M2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new M2Struct__idltest_clones_M2({ value: "s1", str: "s1", i32: 1 }).serialize()));
out.push("idltest.consts.TestPair" + '\t' + "default" + '\t' + JSON.stringify(new TestPair({ value: 1, name: "s1" }).serialize()));
out.push("idltest.datainheritance.ParameterDTO" + '\t' + "default" + '\t' + JSON.stringify(new ParameterDTO({ i32: 1, str: "s1" }).serialize()));
out.push("idltest.datainheritance.TestData1" + '\t' + "default" + '\t' + JSON.stringify(new TestData1({ str: "s1", i32: 1 }).serialize()));
out.push("idltest.datainheritance.TestData2" + '\t' + "default" + '\t' + JSON.stringify(new TestData2({ str: "s1", i32: 1, value: 1 }).serialize()));
out.push("idltest.datainheritance.UserDTO" + '\t' + "default" + '\t' + JSON.stringify(new UserDTO({ value: { i32: 1, str: "s1" } }).serialize()));
out.push("idltest.diamonds.DTO1" + '\t' + "default" + '\t' + JSON.stringify(new DTO1__idltest_diamonds_DTO1({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, if3Field: 2, if2Field: 2 }).serialize()));
out.push("idltest.diamonds.TestInterface1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface1Struct__idltest_diamonds_TestInterface1({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2 }).serialize()));
out.push("idltest.diamonds.TestInterface2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface2Struct__idltest_diamonds_TestInterface2({ if2Field: 2, sameField: 2, sameEverywhereField: 2 }).serialize()));
out.push("idltest.diamonds.TestInterface3.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface3Struct__idltest_diamonds_TestInterface3({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, if3Field: 2 }).serialize()));
out.push("idltest.dtofields.IntPair.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IntPairStruct__idltest_dtofields_IntPair({ x: 1, y: 1 }).serialize()));
out.push("idltest.dtofields.ListObj" + '\t' + "default" + '\t' + JSON.stringify(new ListObj({ all: [{ a: 1 }] }).serialize()));
out.push("idltest.dtofields.Metadata.Struct" + '\t' + "default" + '\t' + JSON.stringify(new MetadataStruct__idltest_dtofields_Metadata({ id: "s1", name: "s1" }).serialize()));
out.push("idltest.dtofields.NullableContent.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NullableContentStruct({ a: 1 }).serialize()));
out.push("idltest.dtofields.NullableObj" + '\t' + "default" + '\t' + JSON.stringify(new NullableObj({ a: 1 }).serialize()));
out.push("idltest.dtofields.OptionalObj" + '\t' + "default" + '\t' + JSON.stringify(new OptionalObj({ no: { a: 1 } }).serialize()));
out.push("idltest.dtofields.Point" + '\t' + "default" + '\t' + JSON.stringify(new Point__idltest_dtofields_Point({ w: 1, h: 1, id: "s1", name: "s1", x: 1, y: 1, ownfield: "s1", export: true }).serialize()));
out.push("idltest.dtofields.PointLike.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PointLikeStruct__idltest_dtofields_PointLike({ id: "s1", name: "s1", x: 1, y: 1 }).serialize()));
out.push("idltest.dtofields.WHPair.Struct" + '\t' + "default" + '\t' + JSON.stringify(new WHPairStruct({ w: 1, h: 1 }).serialize()));
out.push("idltest.enums.EnumHolder" + '\t' + "default" + '\t' + JSON.stringify(new EnumHolder({ en: "Element1" }).serialize()));
out.push("idltest.enums.KVEnumGeneric" + '\t' + "default" + '\t' + JSON.stringify(new KVEnumGeneric({ test: {   ["s1"]: "Element1" } }).serialize()));
out.push("idltest.events.ADTType" + '\t' + "BranchA" + '\t' + JSON.stringify(({ "BranchA": { a: "s1" } })));
out.push("idltest.events.ADTType" + '\t' + "BranchB" + '\t' + JSON.stringify(({ "BranchB": { b: "s1" } })));
out.push("idltest.events.BranchA" + '\t' + "default" + '\t' + JSON.stringify(new BranchA({ a: "s1" }).serialize()));
out.push("idltest.events.BranchB" + '\t' + "default" + '\t' + JSON.stringify(new BranchB({ b: "s1" }).serialize()));
out.push("idltest.identifiers.BucketID" + '\t' + "default" + '\t' + JSON.stringify(new BucketID("BucketID#3a7f0c12-1234-5678-9abc-fedcba987654:s1:3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.identifiers.CompanyId" + '\t' + "default" + '\t' + JSON.stringify(new CompanyId("CompanyId#2:3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.identifiers.ComplexID" + '\t' + "default" + '\t' + JSON.stringify(new ComplexID("ComplexID#BucketID%233a7f0c12-1234-5678-9abc-fedcba987654%3As1%3A3a7f0c12-1234-5678-9abc-fedcba987654:1:s1:3a7f0c12-1234-5678-9abc-fedcba987654:UserWithEnumId%233a7f0c12-1234-5678-9abc-fedcba987654%3AEngineering%3A3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.identifiers.KVIDGeneric" + '\t' + "default" + '\t' + JSON.stringify(new KVIDGeneric({ test: {   ["s1"]: "BucketID#3a7f0c12-1234-5678-9abc-fedcba987654:s1:3a7f0c12-1234-5678-9abc-fedcba987654" } }).serialize()));
out.push("idltest.identifiers.UserId" + '\t' + "default" + '\t' + JSON.stringify(new UserId__idltest_identifiers_UserId("UserId#3a7f0c12-1234-5678-9abc-fedcba987654:3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.identifiers.UserWithEnumId" + '\t' + "default" + '\t' + JSON.stringify(new UserWithEnumId("UserWithEnumId#3a7f0c12-1234-5678-9abc-fedcba987654:Engineering:3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.inheritance.Covariant.Struct" + '\t' + "default" + '\t' + JSON.stringify(new CovariantStruct({  }).serialize()));
out.push("idltest.inheritance.CovariantA.Struct" + '\t' + "default" + '\t' + JSON.stringify(new CovariantAStruct({  }).serialize()));
out.push("idltest.inheritance.CovariantB.Struct" + '\t' + "default" + '\t' + JSON.stringify(new CovariantBStruct({  }).serialize()));
out.push("idltest.inheritance.DataWithAB" + '\t' + "default" + '\t' + JSON.stringify(new DataWithAB({  }).serialize()));
out.push("idltest.inheritance.Empty.Struct" + '\t' + "default" + '\t' + JSON.stringify(new EmptyStruct({  }).serialize()));
out.push("idltest.inheritance.IA1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IA1Struct({ Int: 1 }).serialize()));
out.push("idltest.inheritance.IA2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IA2Struct({ Int: 1 }).serialize()));
out.push("idltest.inheritance.IntPair.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IntPairStruct__idltest_inheritance_IntPair({ x: 1, y: 1 }).serialize()));
out.push("idltest.inheritance.Metadata.Struct" + '\t' + "default" + '\t' + JSON.stringify(new MetadataStruct__idltest_inheritance_Metadata({ id: "s1", name: "s1" }).serialize()));
out.push("idltest.inheritance.Notification.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NotificationStruct({  }).serialize()));
out.push("idltest.inheritance.NotificationWithA.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NotificationWithAStruct({  }).serialize()));
out.push("idltest.inheritance.NotificationWithAB.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NotificationWithABStruct({  }).serialize()));
out.push("idltest.inheritance.NotificationWithB.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NotificationWithBStruct({  }).serialize()));
out.push("idltest.inheritance.Point" + '\t' + "default" + '\t' + JSON.stringify(new Point__idltest_inheritance_Point({ id: "s1", name: "s1", x: 1, y: 1 }).serialize()));
out.push("idltest.inheritance.PointLike.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PointLikeStruct__idltest_inheritance_PointLike({ id: "s1", name: "s1", x: 1, y: 1 }).serialize()));
out.push("idltest.inheritance.Str" + '\t' + "default" + '\t' + JSON.stringify(new Str({ str: "s1" }).serialize()));
out.push("idltest.json.JLBool" + '\t' + "default" + '\t' + JSON.stringify(new JLBool({ value: true }).serialize()));
out.push("idltest.json.JLNull" + '\t' + "default" + '\t' + JSON.stringify(new JLNull({  }).serialize()));
out.push("idltest.json.JLNumber" + '\t' + "default" + '\t' + JSON.stringify(new JLNumber({ value: 2.5 }).serialize()));
out.push("idltest.json.JLString" + '\t' + "default" + '\t' + JSON.stringify(new JLString({ value: "s1" }).serialize()));
out.push("idltest.json.JSONLike" + '\t' + "JLBool" + '\t' + JSON.stringify(({ "JLBool": { value: true } })));
out.push("idltest.json.JSONLike" + '\t' + "JLNull" + '\t' + JSON.stringify(({ "JLNull": {  } })));
out.push("idltest.json.JSONLike" + '\t' + "JLNumber" + '\t' + JSON.stringify(({ "JLNumber": { value: 2.5 } })));
out.push("idltest.json.JSONLike" + '\t' + "JLString" + '\t' + JSON.stringify(({ "JLString": { value: "s1" } })));
out.push("idltest.phase.LengthInBytes.Struct" + '\t' + "default" + '\t' + JSON.stringify(new LengthInBytesStruct({ bytes: 2 }).serialize()));
out.push("idltest.phase.Name.Struct" + '\t' + "default" + '\t' + JSON.stringify(new NameStruct({ name: "s1" }).serialize()));
out.push("idltest.phase.Name_incoming" + '\t' + "default" + '\t' + JSON.stringify(new Name_incoming({ name: "s1" }).serialize()));
out.push("idltest.phase.Name_stored" + '\t' + "default" + '\t' + JSON.stringify(new Name_stored({ name: "s1", bytes: 2 }).serialize()));
out.push("idltest.phase.Name_stored_.Struct" + '\t' + "default" + '\t' + JSON.stringify(new Name_stored_Struct({ name: "s1", bytes: 2 }).serialize()));
out.push("idltest.services.ErrorData.Struct" + '\t' + "default" + '\t' + JSON.stringify(new ErrorDataStruct({ message: "s1" }).serialize()));
out.push("idltest.services.Package" + '\t' + "default" + '\t' + JSON.stringify(new Package({ name: "s1" }).serialize()));
out.push("idltest.services.Request.Struct" + '\t' + "default" + '\t' + JSON.stringify(new RequestStruct({ firstName: "s1", secondName: "s1" }).serialize()));
out.push("idltest.services.SuccessData.Struct" + '\t' + "default" + '\t' + JSON.stringify(new SuccessDataStruct({ greeting: "s1" }).serialize()));
out.push("idltest.services.SuccessDataData" + '\t' + "default" + '\t' + JSON.stringify(new SuccessDataData({ greeting: "s1" }).serialize()));
out.push("idltest.streams.Nuthing" + '\t' + "default" + '\t' + JSON.stringify(new Nuthing({  }).serialize()));
out.push("idltest.substraction.Identified.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IdentifiedStruct({ id: "s1" }).serialize()));
out.push("idltest.substraction.PersonalAttributes.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PersonalAttributesStruct({ ssn: "s1" }).serialize()));
out.push("idltest.substraction.PublicUser1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PublicUser1Struct({ name: "s1" }).serialize()));
out.push("idltest.substraction.PublicUser2" + '\t' + "default" + '\t' + JSON.stringify(new PublicUser2({ name: "s1" }).serialize()));
out.push("idltest.substraction.SecurityAttributes.Struct" + '\t' + "default" + '\t' + JSON.stringify(new SecurityAttributesStruct({ ssn: "s1", password: "s1" }).serialize()));
out.push("idltest.substraction.User1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new User1Struct({ name: "s1", id: "s1", pass: "s1" }).serialize()));
out.push("idltest.substraction.User2" + '\t' + "default" + '\t' + JSON.stringify(new User2({ ssn: "s1", password: "s1", name: "s1" }).serialize()));
out.push("idltest.substraction.UserId" + '\t' + "default" + '\t' + JSON.stringify(new UserId__idltest_substraction_UserId("UserId#3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("idltest.syntax.Ast" + '\t' + "TestDto" + '\t' + JSON.stringify(({ "TestDto": { value: {  } } })));
out.push("idltest.syntax.Ast" + '\t' + "TestMixin" + '\t' + JSON.stringify(({ "TestMixin": {  } })));
out.push("idltest.syntax.Ast" + '\t' + "TestOneliners" + '\t' + JSON.stringify(({ "TestOneliners": { testDto: { value: {  } }, str: "s1", i08: 1 } })));
out.push("idltest.syntax.TestId" + '\t' + "default" + '\t' + JSON.stringify(new TestId("TestId#s1").serialize()));
out.push("idltest.syntax.TestId1" + '\t' + "default" + '\t' + JSON.stringify(new TestId1("TestId1#s1").serialize()));
out.push("idltest.syntax.TestMixin.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestMixinStruct({  }).serialize()));
out.push("idltest.upcasts.Identifiable.Struct" + '\t' + "default" + '\t' + JSON.stringify(new IdentifiableStruct({ id: "3a7f0c12-1234-5678-9abc-fedcba987654" }).serialize()));
out.push("idltest.upcasts.Item" + '\t' + "default" + '\t' + JSON.stringify(new Item({ id: "3a7f0c12-1234-5678-9abc-fedcba987654", name: "s1", price: 1 }).serialize()));
out.push("idltest.upcasts.ItemContent.Struct" + '\t' + "default" + '\t' + JSON.stringify(new ItemContentStruct({ id: "3a7f0c12-1234-5678-9abc-fedcba987654", name: "s1" }).serialize()));
out.push("izumi.test.domain01.AnAdt" + '\t' + "AnotherMember" + '\t' + JSON.stringify(({ "AnotherMember": { boolField: true } })));
out.push("izumi.test.domain01.AnAdt" + '\t' + "TestObject" + '\t' + JSON.stringify(({ "TestObject": { userId: "s1", accountBalance: 1, latestLogin: 2, keys: {   ["s1"]: "s1" }, nicknames: ["s1"] } })));
out.push("izumi.test.domain01.AnotherTestObject" + '\t' + "default" + '\t' + JSON.stringify(new AnotherTestObject({ parent_embedded: "s1", parent: "s1", embedded: true, own: 1 }).serialize()));
out.push("izumi.test.domain01.AnyValTest.Struct" + '\t' + "default" + '\t' + JSON.stringify(new AnyValTestStruct({ boolField: true }).serialize()));
out.push("izumi.test.domain01.BasicFailure" + '\t' + "default" + '\t' + JSON.stringify(new BasicFailure({ code: 1 }).serialize()));
out.push("izumi.test.domain01.CommonFailure.Struct" + '\t' + "default" + '\t' + JSON.stringify(new CommonFailureStruct({ code: 1 }).serialize()));
out.push("izumi.test.domain01.ExtendedMixin.Struct" + '\t' + "default" + '\t' + JSON.stringify(new ExtendedMixinStruct({ parent_embedded: "s1", parent: "s1", embedded: true, own: 1 }).serialize()));
out.push("izumi.test.domain01.GenericFailure" + '\t' + "default" + '\t' + JSON.stringify(new GenericFailure({ message: "s1", diagnostics: "s1", reserved: {   ["s1"]: "s1" }, code: "EntityNotFound" }).serialize()));
out.push("izumi.test.domain01.GenericFailureData.Struct" + '\t' + "default" + '\t' + JSON.stringify(new GenericFailureDataStruct({ message: "s1", diagnostics: "s1", reserved: {   ["s1"]: "s1" } }).serialize()));
out.push("izumi.test.domain01.GoAliasTest.Struct" + '\t' + "default" + '\t' + JSON.stringify(new GoAliasTestStruct({ a: "s1" }).serialize()));
out.push("izumi.test.domain01.IDForDomain2" + '\t' + "default" + '\t' + JSON.stringify(new IDForDomain2("IDForDomain2#1").serialize()));
out.push("izumi.test.domain01.ImportAppId" + '\t' + "default" + '\t' + JSON.stringify(new ImportAppId("ImportAppId#3a7f0c12-1234-5678-9abc-fedcba987654").serialize()));
out.push("izumi.test.domain01.NestedClass" + '\t' + "default" + '\t' + JSON.stringify(new NestedClass({ c: { c: undefined } }).serialize()));
out.push("izumi.test.domain01.OffsetLimit" + '\t' + "default" + '\t' + JSON.stringify(new OffsetLimit({ offset: 1, limit: 2 }).serialize()));
out.push("izumi.test.domain01.PrivateMixin.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PrivateMixinStruct({ parent_embedded: "s1", parent: "s1", embedded: true }).serialize()));
out.push("izumi.test.domain01.PrivateMixinParent.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PrivateMixinParentStruct({ parent: "s1" }).serialize()));
out.push("izumi.test.domain01.PrivateMixinPrivateParent.Struct" + '\t' + "default" + '\t' + JSON.stringify(new PrivateMixinPrivateParentStruct({ parent_embedded: "s1" }).serialize()));
out.push("izumi.test.domain01.PrivateTestObject" + '\t' + "default" + '\t' + JSON.stringify(new PrivateTestObject({ parent_embedded: "s1", parent: "s1", embedded: true, own: 1 }).serialize()));
out.push("izumi.test.domain01.RTestMixin.Struct" + '\t' + "default" + '\t' + JSON.stringify(new RTestMixinStruct({ a: "A" }).serialize()));
out.push("izumi.test.domain01.TestIdentifier" + '\t' + "default" + '\t' + JSON.stringify(new TestIdentifier("TestIdentifier#s1:s1:1").serialize()));
out.push("izumi.test.domain01.TestInterface.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterfaceStruct({ userId: "s1", accountBalance: 1, latestLogin: 2, keys: {   ["s1"]: "s1" }, nicknames: ["s1"] }).serialize()));
out.push("izumi.test.domain01.TestObject" + '\t' + "default" + '\t' + JSON.stringify(new TestObject({ userId: "s1", accountBalance: 1, latestLogin: 2, keys: {   ["s1"]: "s1" }, nicknames: ["s1"] }).serialize()));
out.push("izumi.test.domain01.TestValIdentifier" + '\t' + "default" + '\t' + JSON.stringify(new TestValIdentifier("TestValIdentifier#s1").serialize()));
out.push("izumi.test.domain02.Adt2" + '\t' + "default" + '\t' + JSON.stringify(new Adt2({ b: 1 }).serialize()));
out.push("izumi.test.domain02.AdtA" + '\t' + "AdtA1" + '\t' + JSON.stringify(({ "AdtA1": { a: 1 } })));
out.push("izumi.test.domain02.AdtA" + '\t' + "AdtA2" + '\t' + JSON.stringify(({ "AdtA2": { b: 1 } })));
out.push("izumi.test.domain02.AdtA1" + '\t' + "default" + '\t' + JSON.stringify(new AdtA1({ a: 1 }).serialize()));
out.push("izumi.test.domain02.AdtA2" + '\t' + "default" + '\t' + JSON.stringify(new AdtA2({ b: 1 }).serialize()));
out.push("izumi.test.domain02.AliasedUsageData" + '\t' + "default" + '\t' + JSON.stringify(new AliasedUsageData({ testObj: { userId: "s1", accountBalance: 1, latestLogin: 2, keys: {   ["s1"]: "s1" }, nicknames: ["s1"] }, enumField: "Val1" }).serialize()));
out.push("izumi.test.domain02.DTO1" + '\t' + "default" + '\t' + JSON.stringify(new DTO1__izumi_test_domain02_DTO1({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, fromOtherDomain: "TestValIdentifier#s1", fromOtherDomainDirect: "TestValIdentifier#s1", if3Field: 2, if2Field: 2 }).serialize()));
out.push("izumi.test.domain02.Pair1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new Pair1Struct({ x: "s1", y: "s1" }).serialize()));
out.push("izumi.test.domain02.Pair2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new Pair2Struct({ y: "s1", x: "s1" }).serialize()));
out.push("izumi.test.domain02.SomeResp" + '\t' + "DTO1" + '\t' + JSON.stringify(({ "DTO1": { if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, fromOtherDomain: "TestValIdentifier#s1", fromOtherDomainDirect: "TestValIdentifier#s1", if3Field: 2, if2Field: 2 } })));
out.push("izumi.test.domain02.SomeResp" + '\t' + "ImportedBasicFailure" + '\t' + JSON.stringify(({ "ImportedBasicFailure": { code: 1 } })));
out.push("izumi.test.domain02.TestDataWithAlias" + '\t' + "default" + '\t' + JSON.stringify(new TestDataWithAlias({ a: "A" }).serialize()));
out.push("izumi.test.domain02.TestIDReturn" + '\t' + "default" + '\t' + JSON.stringify(new TestIDReturn("TestIDReturn#1").serialize()));
out.push("izumi.test.domain02.TestInterface1.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface1Struct__izumi_test_domain02_TestInterface1({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, fromOtherDomain: "TestValIdentifier#s1", fromOtherDomainDirect: "TestValIdentifier#s1" }).serialize()));
out.push("izumi.test.domain02.TestInterface2.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface2Struct__izumi_test_domain02_TestInterface2({ if2Field: 2, sameField: 2, sameEverywhereField: 2 }).serialize()));
out.push("izumi.test.domain02.TestInterface3.Struct" + '\t' + "default" + '\t' + JSON.stringify(new TestInterface3Struct__izumi_test_domain02_TestInterface3({ if1Field_overriden: 1, if1Field_inherited: 1, sameField: 2, sameEverywhereField: 2, fromOtherDomain: "TestValIdentifier#s1", fromOtherDomainDirect: "TestValIdentifier#s1", if3Field: 2 }).serialize()));
out.push("overlaytest.withoverlay.Email" + '\t' + "default" + '\t' + JSON.stringify(new Email({ attributes: { disposable: true } }).serialize()));
out.push("overlaytest.withoverlay.OverlayEmailAttributes" + '\t' + "default" + '\t' + JSON.stringify(new OverlayEmailAttributes({ disposable: true }).serialize()));
out.push("overlaytest.withoverlay.OverlayUserAttributes" + '\t' + "default" + '\t' + JSON.stringify(new OverlayUserAttributes({ name: "s1", surname: "s1" }).serialize()));
out.push("overlaytest.withoverlay.User" + '\t' + "default" + '\t' + JSON.stringify(new User({ id: "3a7f0c12-1234-5678-9abc-fedcba987654", attributes: { name: "s1", surname: "s1" } }).serialize()));

out.sort();
for (const l of out) console.log(l);

// ---- Skipped wireIds (service/buzzer ephemerals; not exported in TS) ----
// # x-skip-positional  idltest.anyvals.UserData.Struct\tdefault
// # x-skip-positional  idltest.ast.AppNode.Struct\tdefault
// # x-skip-positional  idltest.ast.IfNode.Struct\tdefault
// # x-skip-positional  idltest.ast.LamNode.Struct\tdefault
// # x-skip-positional  idltest.ast.TAppNode.Struct\tdefault
// # x-skip-positional  idltest.ast.TIfNode.Struct\tdefault
// # x-skip-positional  idltest.ast.TLamNode.Struct\tdefault
// # x-skip-positional  idltest.datainheritancetransitive.Coupon\tdefault
// # x-skip-positional  idltest.datainheritancetransitive.CouponData.Struct\tdefault
// # x-skip-positional  idltest.datainheritancetransitive.MassCoupon\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.AdtInputInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.AdtInputOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.AdtInputVoidInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.AdtInputVoidOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EmptyInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EmptyOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EnumInputInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EnumInputOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EnumInputVoidInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.EnumInputVoidOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.HelloInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.HelloOutput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.UserRegisteredInput\tdefault
// # x-skip-positional  idltest.events.TestBuzzer.UserRegisteredOutput\tdefault
// # x-skip-positional  idltest.inheritance.CovariantDTO1\tdefault
// # x-skip-positional  idltest.inheritance.CovariantDTO2\tdefault
// # x-skip-positional  idltest.inheritance.InheritedCovariant.Struct\tdefault
// # x-skip-positional  idltest.inheritance.NotiBase.Struct\tdefault
// # x-skip-positional  idltest.inheritance.NotiWithFile.Struct\tdefault
// # x-skip-positional  idltest.inheritance.NotiWithFileRevision.Struct\tdefault
// # x-skip-positional  idltest.inheritance.WithCovariance.Struct\tdefault
// # x-skip-positional  idltest.json.JLArray\tdefault
// # x-skip-positional  idltest.json.JLObject\tdefault
// # x-skip-positional  idltest.json.JSONLike\tJLArray
// # x-skip-positional  idltest.json.JSONLike\tJLObject
// # x-skip-positional  idltest.phase.Name_view\tdefault
// # x-skip-positional  idltest.services.TestService.AlternativeGeneric2Input\tdefault
// # x-skip-positional  idltest.services.TestService.AlternativeGeneric2Output\tFailure
// # x-skip-positional  idltest.services.TestService.AlternativeGeneric2Output\tSuccess
// # x-skip-positional  idltest.services.TestService.AlternativeGenericInput\tdefault
// # x-skip-positional  idltest.services.TestService.AlternativeGenericOutput\tFailure
// # x-skip-positional  idltest.services.TestService.AlternativeGenericOutput\tSuccess
// # x-skip-positional  idltest.services.TestService.AlternativeInput\tdefault
// # x-skip-positional  idltest.services.TestService.AlternativeOutput\tFailure
// # x-skip-positional  idltest.services.TestService.AlternativeOutput\tSuccess
// # x-skip-positional  idltest.services.TestService.AlternativeSameInput\tdefault
// # x-skip-positional  idltest.services.TestService.AlternativeSameOutput\tFailure
// # x-skip-positional  idltest.services.TestService.AlternativeSameOutput\tSuccess
// # x-skip-positional  idltest.services.TestService.AnotherVoidInput\tdefault
// # x-skip-positional  idltest.services.TestService.AnotherVoidOutput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicMultilineSyntaxInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicMultilineSyntaxOutput\tErrorData
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicMultilineSyntaxOutput\tSuccessDataData
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicOutInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicOutOutput\tErrorData
// # x-skip-positional  idltest.services.TestService.GreetAlgebraicOutOutput\tSuccessDataData
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructMultilineSyntaxInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructMultilineSyntaxOutput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructOutInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructOutOutput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructureMultilineCurlyBracesSyntaxInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetImplicitStructureMultilineCurlyBracesSyntaxOutput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetSingularOutInput\tdefault
// # x-skip-positional  idltest.services.TestService.GreetSingularOutOutput\tdefault
// # x-skip-positional  idltest.services.TestService.ParameterlessInput\tdefault
// # x-skip-positional  idltest.services.TestService.ParameterlessOutput\tdefault
// # x-skip-positional  idltest.services.TestService.ReturnsListInput\tdefault
// # x-skip-positional  idltest.services.TestService.ReturnsListOutput\tdefault
// # x-skip-positional  idltest.services.TestService.ReturnsMapInput\tdefault
// # x-skip-positional  idltest.services.TestService.ReturnsMapOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleEnum2Input\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleEnum2Output\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleEnumInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleEnumOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleGoReservedInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleGoReservedOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleIntMethodInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleIntMethodOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleMethodInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleMethodOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleMethodWithGenericsInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleMethodWithGenericsOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleOutput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleVoidInput\tdefault
// # x-skip-positional  idltest.services.TestService.SimpleVoidOutput\tdefault
// # x-skip-positional  idltest.services.TestService.UnitResultInput\tdefault
// # x-skip-positional  idltest.services.TestService.UnitResultOutput\tdefault
// # x-skip-positional  idltest.services.TestService.UnitToUnitInput\tdefault
// # x-skip-positional  idltest.services.TestService.UnitToUnitOutput\tdefault
// # x-skip-positional  idltest.syntax.TestDto\tdefault
// # x-skip-positional  idltest.syntax.TestDto1\tdefault
// # x-skip-positional  idltest.syntax.TestOneliners\tdefault
// # x-skip-positional  izumi.test.domain01.AllTypes.Struct\tdefault
// # x-skip-positional  izumi.test.domain01.AllTypesObject\tdefault
// # x-skip-positional  izumi.test.domain01.AnAdt\tAllTypes
// # x-skip-positional  izumi.test.domain01.AnyValTest2.Struct\tdefault
// # x-skip-positional  izumi.test.domain01.GoTimeImportOptional\tdefault
// # x-skip-positional  izumi.test.domain01.OptionalService.OptionalMethodInput\tdefault
// # x-skip-positional  izumi.test.domain01.OptionalService.OptionalMethodOutput\tdefault
// # x-skip-positional  izumi.test.domain01.RTestObject1\tdefault
// # x-skip-positional  izumi.test.domain01.RTestObject2\tdefault
// # x-skip-positional  izumi.test.domain01.RtestMixin2.Struct\tdefault
// # x-skip-positional  izumi.test.domain01.TsuData\tdefault
// # x-skip-positional  izumi.test.domain02.ImportIdService.MixiInput\tdefault
// # x-skip-positional  izumi.test.domain02.ImportIdService.MixiOutput\tAdtA2
// # x-skip-positional  izumi.test.domain02.ImportIdService.MixiOutput\tGenericFailureData
// # x-skip-positional  izumi.test.domain02.ImportIdService.SomeInput\tdefault
// # x-skip-positional  izumi.test.domain02.ImportIdService.SomeOutput\tdefault
// # x-skip-positional  izumi.test.domain02.ImportIdService.UpdateInput\tdefault
// # x-skip-positional  izumi.test.domain02.ImportIdService.UpdateOutput\tAdtA2
// # x-skip-positional  izumi.test.domain02.ImportIdService.UpdateOutput\tGenericFailure
// # x-skip-positional  izumi.test.domain02.ImportIdTest.Struct\tdefault
// # x-skip-positional  izumi.test.domain02.NestedAdtsService.AdtNestedInput\tdefault
// # x-skip-positional  izumi.test.domain02.NestedAdtsService.AdtNestedOutput\tAdt2
// # x-skip-positional  izumi.test.domain02.NestedAdtsService.AdtNestedOutput\tAdtA
// # x-skip-positional  izumi.test.domain02.TestAliasServ.GetMassCouponsInput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.GetMassCouponsOutput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.IfaceMethodInput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.IfaceMethodOutput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdImportedReturnInput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdImportedReturnOutput\tDTO1
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdImportedReturnOutput\tImportedIDForDomain2
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdReturnInput\tdefault
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdReturnOutput\tDTO1
// # x-skip-positional  izumi.test.domain02.TestAliasServ.TestADTIdReturnOutput\tTestIDReturn
